# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_folder_file_manager_response_links_item import GetFolderFileManagerResponseLinksItem


class GetFolderFileManagerResponse(UniversalBaseModel):
    """
    An individual folder listed in the File Manager.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[GetFolderFileManagerResponseLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time a file was added to the File Manager in ISO 8601 format.
    """

    created_by: typing.Optional[str] = pydantic.Field(default=None)
    """
    The username of the profile that created the folder.
    """

    file_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of files in the folder.
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    The unique id for the folder.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the folder.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
