# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.gallery_file import GalleryFile
from .list_files_file_manager_response_links_item import ListFilesFileManagerResponseLinksItem


class ListFilesFileManagerResponse(UniversalBaseModel):
    """
    A list of available images and files stored in the File Manager for the account.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[ListFilesFileManagerResponseLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    files: typing.Optional[typing.List[GalleryFile]] = pydantic.Field(default=None)
    """
     A list of files and images in an account.
    """

    total_file_size: typing.Optional[float] = pydantic.Field(default=None)
    """
    The total size of all File Manager files in bytes.
    """

    total_items: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of items matching the query regardless of pagination.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
