# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_audience_contact_request_data_mode import CreateAudienceContactRequestDataMode
    from .create_audience_contact_request_email_channel import CreateAudienceContactRequestEmailChannel
    from .create_audience_contact_request_email_channel_marketing_consent import (
        CreateAudienceContactRequestEmailChannelMarketingConsent,
    )
    from .create_audience_contact_request_email_channel_marketing_consent_status import (
        CreateAudienceContactRequestEmailChannelMarketingConsentStatus,
    )
    from .create_audience_contact_request_merge_field_validation_mode import (
        CreateAudienceContactRequestMergeFieldValidationMode,
    )
    from .create_audience_contact_request_merge_fields_value import CreateAudienceContactRequestMergeFieldsValue
    from .create_audience_contact_request_merge_fields_value_addr1 import (
        CreateAudienceContactRequestMergeFieldsValueAddr1,
    )
    from .create_audience_contact_request_sms_channel import CreateAudienceContactRequestSmsChannel
    from .create_audience_contact_request_sms_channel_marketing_consent import (
        CreateAudienceContactRequestSmsChannelMarketingConsent,
    )
    from .create_audience_contact_request_sms_channel_marketing_consent_source import (
        CreateAudienceContactRequestSmsChannelMarketingConsentSource,
    )
    from .create_audience_contact_request_sms_channel_marketing_consent_status import (
        CreateAudienceContactRequestSmsChannelMarketingConsentStatus,
    )
    from .create_audience_contact_request_tags_item import CreateAudienceContactRequestTagsItem
    from .create_audience_contact_request_tags_item_name import CreateAudienceContactRequestTagsItemName
    from .create_audience_contact_request_tags_item_name_status import CreateAudienceContactRequestTagsItemNameStatus
    from .get_audience_contact_list_request_sort_dir import GetAudienceContactListRequestSortDir
    from .get_audience_contact_list_request_sort_field import GetAudienceContactListRequestSortField
    from .get_audience_contact_list_response import GetAudienceContactListResponse
    from .get_audience_contact_list_response_links_item import GetAudienceContactListResponseLinksItem
    from .get_audience_contact_list_response_links_item_method import GetAudienceContactListResponseLinksItemMethod
    from .patch_audience_contact_request_data_mode import PatchAudienceContactRequestDataMode
    from .patch_audience_contact_request_email_channel import PatchAudienceContactRequestEmailChannel
    from .patch_audience_contact_request_email_channel_marketing_consent import (
        PatchAudienceContactRequestEmailChannelMarketingConsent,
    )
    from .patch_audience_contact_request_email_channel_marketing_consent_source import (
        PatchAudienceContactRequestEmailChannelMarketingConsentSource,
    )
    from .patch_audience_contact_request_email_channel_marketing_consent_status import (
        PatchAudienceContactRequestEmailChannelMarketingConsentStatus,
    )
    from .patch_audience_contact_request_merge_field_validation_mode import (
        PatchAudienceContactRequestMergeFieldValidationMode,
    )
    from .patch_audience_contact_request_merge_fields_value import PatchAudienceContactRequestMergeFieldsValue
    from .patch_audience_contact_request_merge_fields_value_addr1 import (
        PatchAudienceContactRequestMergeFieldsValueAddr1,
    )
    from .patch_audience_contact_request_sms_channel import PatchAudienceContactRequestSmsChannel
    from .patch_audience_contact_request_sms_channel_marketing_consent import (
        PatchAudienceContactRequestSmsChannelMarketingConsent,
    )
    from .patch_audience_contact_request_sms_channel_marketing_consent_source import (
        PatchAudienceContactRequestSmsChannelMarketingConsentSource,
    )
    from .patch_audience_contact_request_sms_channel_marketing_consent_status import (
        PatchAudienceContactRequestSmsChannelMarketingConsentStatus,
    )
    from .patch_audience_contact_request_tags_item import PatchAudienceContactRequestTagsItem
    from .patch_audience_contact_request_tags_item_name import PatchAudienceContactRequestTagsItemName
    from .patch_audience_contact_request_tags_item_name_status import PatchAudienceContactRequestTagsItemNameStatus
_dynamic_imports: typing.Dict[str, str] = {
    "CreateAudienceContactRequestDataMode": ".create_audience_contact_request_data_mode",
    "CreateAudienceContactRequestEmailChannel": ".create_audience_contact_request_email_channel",
    "CreateAudienceContactRequestEmailChannelMarketingConsent": ".create_audience_contact_request_email_channel_marketing_consent",
    "CreateAudienceContactRequestEmailChannelMarketingConsentStatus": ".create_audience_contact_request_email_channel_marketing_consent_status",
    "CreateAudienceContactRequestMergeFieldValidationMode": ".create_audience_contact_request_merge_field_validation_mode",
    "CreateAudienceContactRequestMergeFieldsValue": ".create_audience_contact_request_merge_fields_value",
    "CreateAudienceContactRequestMergeFieldsValueAddr1": ".create_audience_contact_request_merge_fields_value_addr1",
    "CreateAudienceContactRequestSmsChannel": ".create_audience_contact_request_sms_channel",
    "CreateAudienceContactRequestSmsChannelMarketingConsent": ".create_audience_contact_request_sms_channel_marketing_consent",
    "CreateAudienceContactRequestSmsChannelMarketingConsentSource": ".create_audience_contact_request_sms_channel_marketing_consent_source",
    "CreateAudienceContactRequestSmsChannelMarketingConsentStatus": ".create_audience_contact_request_sms_channel_marketing_consent_status",
    "CreateAudienceContactRequestTagsItem": ".create_audience_contact_request_tags_item",
    "CreateAudienceContactRequestTagsItemName": ".create_audience_contact_request_tags_item_name",
    "CreateAudienceContactRequestTagsItemNameStatus": ".create_audience_contact_request_tags_item_name_status",
    "GetAudienceContactListRequestSortDir": ".get_audience_contact_list_request_sort_dir",
    "GetAudienceContactListRequestSortField": ".get_audience_contact_list_request_sort_field",
    "GetAudienceContactListResponse": ".get_audience_contact_list_response",
    "GetAudienceContactListResponseLinksItem": ".get_audience_contact_list_response_links_item",
    "GetAudienceContactListResponseLinksItemMethod": ".get_audience_contact_list_response_links_item_method",
    "PatchAudienceContactRequestDataMode": ".patch_audience_contact_request_data_mode",
    "PatchAudienceContactRequestEmailChannel": ".patch_audience_contact_request_email_channel",
    "PatchAudienceContactRequestEmailChannelMarketingConsent": ".patch_audience_contact_request_email_channel_marketing_consent",
    "PatchAudienceContactRequestEmailChannelMarketingConsentSource": ".patch_audience_contact_request_email_channel_marketing_consent_source",
    "PatchAudienceContactRequestEmailChannelMarketingConsentStatus": ".patch_audience_contact_request_email_channel_marketing_consent_status",
    "PatchAudienceContactRequestMergeFieldValidationMode": ".patch_audience_contact_request_merge_field_validation_mode",
    "PatchAudienceContactRequestMergeFieldsValue": ".patch_audience_contact_request_merge_fields_value",
    "PatchAudienceContactRequestMergeFieldsValueAddr1": ".patch_audience_contact_request_merge_fields_value_addr1",
    "PatchAudienceContactRequestSmsChannel": ".patch_audience_contact_request_sms_channel",
    "PatchAudienceContactRequestSmsChannelMarketingConsent": ".patch_audience_contact_request_sms_channel_marketing_consent",
    "PatchAudienceContactRequestSmsChannelMarketingConsentSource": ".patch_audience_contact_request_sms_channel_marketing_consent_source",
    "PatchAudienceContactRequestSmsChannelMarketingConsentStatus": ".patch_audience_contact_request_sms_channel_marketing_consent_status",
    "PatchAudienceContactRequestTagsItem": ".patch_audience_contact_request_tags_item",
    "PatchAudienceContactRequestTagsItemName": ".patch_audience_contact_request_tags_item_name",
    "PatchAudienceContactRequestTagsItemNameStatus": ".patch_audience_contact_request_tags_item_name_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateAudienceContactRequestDataMode",
    "CreateAudienceContactRequestEmailChannel",
    "CreateAudienceContactRequestEmailChannelMarketingConsent",
    "CreateAudienceContactRequestEmailChannelMarketingConsentStatus",
    "CreateAudienceContactRequestMergeFieldValidationMode",
    "CreateAudienceContactRequestMergeFieldsValue",
    "CreateAudienceContactRequestMergeFieldsValueAddr1",
    "CreateAudienceContactRequestSmsChannel",
    "CreateAudienceContactRequestSmsChannelMarketingConsent",
    "CreateAudienceContactRequestSmsChannelMarketingConsentSource",
    "CreateAudienceContactRequestSmsChannelMarketingConsentStatus",
    "CreateAudienceContactRequestTagsItem",
    "CreateAudienceContactRequestTagsItemName",
    "CreateAudienceContactRequestTagsItemNameStatus",
    "GetAudienceContactListRequestSortDir",
    "GetAudienceContactListRequestSortField",
    "GetAudienceContactListResponse",
    "GetAudienceContactListResponseLinksItem",
    "GetAudienceContactListResponseLinksItemMethod",
    "PatchAudienceContactRequestDataMode",
    "PatchAudienceContactRequestEmailChannel",
    "PatchAudienceContactRequestEmailChannelMarketingConsent",
    "PatchAudienceContactRequestEmailChannelMarketingConsentSource",
    "PatchAudienceContactRequestEmailChannelMarketingConsentStatus",
    "PatchAudienceContactRequestMergeFieldValidationMode",
    "PatchAudienceContactRequestMergeFieldsValue",
    "PatchAudienceContactRequestMergeFieldsValueAddr1",
    "PatchAudienceContactRequestSmsChannel",
    "PatchAudienceContactRequestSmsChannelMarketingConsent",
    "PatchAudienceContactRequestSmsChannelMarketingConsentSource",
    "PatchAudienceContactRequestSmsChannelMarketingConsentStatus",
    "PatchAudienceContactRequestTagsItem",
    "PatchAudienceContactRequestTagsItemName",
    "PatchAudienceContactRequestTagsItemNameStatus",
]
