# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_automations_request_trigger_settings_workflow_type import (
    CreateAutomationsRequestTriggerSettingsWorkflowType,
)


class CreateAutomationsRequestTriggerSettings(UniversalBaseModel):
    """
    Trigger settings for the Automation.
    """

    workflow_type: CreateAutomationsRequestTriggerSettingsWorkflowType = pydantic.Field()
    """
    The type of Automation workflow.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
