# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.unsubscribes import Unsubscribes
from .list_unsubscribed_reports_response_links_item import ListUnsubscribedReportsResponseLinksItem


class ListUnsubscribedReportsResponse(UniversalBaseModel):
    """
    A list of members who have unsubscribed from a specific campaign.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[ListUnsubscribedReportsResponseLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    campaign_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The campaign id.
    """

    total_items: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of items matching the query regardless of pagination.
    """

    unsubscribes: typing.Optional[typing.List[Unsubscribes]] = pydantic.Field(default=None)
    """
    An array of objects, each representing a member who unsubscribed from a campaign.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
