# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .list_advice_reports_response_advice_item_links_item import ListAdviceReportsResponseAdviceItemLinksItem
from .list_advice_reports_response_advice_item_type import ListAdviceReportsResponseAdviceItemType


class ListAdviceReportsResponseAdviceItem(UniversalBaseModel):
    """
    Campaign feedback details.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[ListAdviceReportsResponseAdviceItemLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    The advice message.
    """

    type: typing.Optional[ListAdviceReportsResponseAdviceItemType] = pydantic.Field(default=None)
    """
    The sentiment type for a feedback message.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
