# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListEepurlReportsResponseTwitterStatusesItem(UniversalBaseModel):
    """
    An individual tweet.
    """

    datetime: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    A timestamp for the tweet.
    """

    is_retweet: typing.Optional[bool] = pydantic.Field(default=None)
    """
    A 'true' or 'false' status of whether the tweet is a retweet.
    """

    screen_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Twitter handle for the author of the tweet.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    The body of the tweet.
    """

    status_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The individual id for the tweet.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
