# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_eepurl_reports_response_twitter_statuses_item import ListEepurlReportsResponseTwitterStatusesItem


class ListEepurlReportsResponseTwitter(UniversalBaseModel):
    """
    A summary of Twitter activity for a campaign.
    """

    first_tweet: typing.Optional[str] = pydantic.Field(default=None)
    """
    The day and time of the first recorded tweet with a link to the campaign.
    """

    last_tweet: typing.Optional[str] = pydantic.Field(default=None)
    """
    The day and time of the last recorded tweet with a link to the campaign.
    """

    retweets: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of retweets that include a link to the campaign.
    """

    statuses: typing.Optional[typing.List[ListEepurlReportsResponseTwitterStatusesItem]] = pydantic.Field(default=None)
    """
    A summary of tweets that include a link to the campaign.
    """

    tweets: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of tweets including a link to the campaign.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
