# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.abuse_complaint import AbuseComplaint
from .list_abuse_reports_reports_response_links_item import ListAbuseReportsReportsResponseLinksItem


class ListAbuseReportsReportsResponse(UniversalBaseModel):
    """
    A list of abuse complaints for a specific list.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[ListAbuseReportsReportsResponseLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    abuse_reports: typing.Optional[typing.List[AbuseComplaint]] = pydantic.Field(default=None)
    """
    An array of objects, each representing an abuse report resource.
    """

    campaign_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The campaign id.
    """

    total_items: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of items matching the query regardless of pagination.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
