# This file was auto-generated by Fern from our API Definition.

import typing

GetVerifiedDomainsResponseStatus = typing.Union[
    typing.Literal[
        "VERIFICATION_IN_PROGRESS",
        "VERIFIED",
        "EXPIRED",
        "ERROR",
        "AUTHENTICATION_IN_PROGRESS",
        "AUTHENTICATION_ERROR",
        "AUTHENTICATED",
    ],
    typing.Any,
]
