# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_verified_domains_response_domains_item import ListVerifiedDomainsResponseDomainsItem


class ListVerifiedDomainsResponse(UniversalBaseModel):
    """
    The verified domains currently on the account.
    """

    domains: typing.Optional[typing.List[ListVerifiedDomainsResponseDomainsItem]] = pydantic.Field(default=None)
    """
    The domains on the account
    """

    total_items: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of items matching the query regardless of pagination.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
