# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_template_folders_response import CreateTemplateFoldersResponse
    from .create_template_folders_response_links_item import CreateTemplateFoldersResponseLinksItem
    from .create_template_folders_response_links_item_method import CreateTemplateFoldersResponseLinksItemMethod
    from .get_template_folders_response import GetTemplateFoldersResponse
    from .get_template_folders_response_links_item import GetTemplateFoldersResponseLinksItem
    from .get_template_folders_response_links_item_method import GetTemplateFoldersResponseLinksItemMethod
    from .list_template_folders_response import ListTemplateFoldersResponse
    from .list_template_folders_response_folders_item import ListTemplateFoldersResponseFoldersItem
    from .list_template_folders_response_folders_item_links_item import ListTemplateFoldersResponseFoldersItemLinksItem
    from .list_template_folders_response_folders_item_links_item_method import (
        ListTemplateFoldersResponseFoldersItemLinksItemMethod,
    )
    from .list_template_folders_response_links_item import ListTemplateFoldersResponseLinksItem
    from .list_template_folders_response_links_item_method import ListTemplateFoldersResponseLinksItemMethod
    from .update_template_folders_response import UpdateTemplateFoldersResponse
    from .update_template_folders_response_links_item import UpdateTemplateFoldersResponseLinksItem
    from .update_template_folders_response_links_item_method import UpdateTemplateFoldersResponseLinksItemMethod
_dynamic_imports: typing.Dict[str, str] = {
    "CreateTemplateFoldersResponse": ".create_template_folders_response",
    "CreateTemplateFoldersResponseLinksItem": ".create_template_folders_response_links_item",
    "CreateTemplateFoldersResponseLinksItemMethod": ".create_template_folders_response_links_item_method",
    "GetTemplateFoldersResponse": ".get_template_folders_response",
    "GetTemplateFoldersResponseLinksItem": ".get_template_folders_response_links_item",
    "GetTemplateFoldersResponseLinksItemMethod": ".get_template_folders_response_links_item_method",
    "ListTemplateFoldersResponse": ".list_template_folders_response",
    "ListTemplateFoldersResponseFoldersItem": ".list_template_folders_response_folders_item",
    "ListTemplateFoldersResponseFoldersItemLinksItem": ".list_template_folders_response_folders_item_links_item",
    "ListTemplateFoldersResponseFoldersItemLinksItemMethod": ".list_template_folders_response_folders_item_links_item_method",
    "ListTemplateFoldersResponseLinksItem": ".list_template_folders_response_links_item",
    "ListTemplateFoldersResponseLinksItemMethod": ".list_template_folders_response_links_item_method",
    "UpdateTemplateFoldersResponse": ".update_template_folders_response",
    "UpdateTemplateFoldersResponseLinksItem": ".update_template_folders_response_links_item",
    "UpdateTemplateFoldersResponseLinksItemMethod": ".update_template_folders_response_links_item_method",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateTemplateFoldersResponse",
    "CreateTemplateFoldersResponseLinksItem",
    "CreateTemplateFoldersResponseLinksItemMethod",
    "GetTemplateFoldersResponse",
    "GetTemplateFoldersResponseLinksItem",
    "GetTemplateFoldersResponseLinksItemMethod",
    "ListTemplateFoldersResponse",
    "ListTemplateFoldersResponseFoldersItem",
    "ListTemplateFoldersResponseFoldersItemLinksItem",
    "ListTemplateFoldersResponseFoldersItemLinksItemMethod",
    "ListTemplateFoldersResponseLinksItem",
    "ListTemplateFoldersResponseLinksItemMethod",
    "UpdateTemplateFoldersResponse",
    "UpdateTemplateFoldersResponseLinksItem",
    "UpdateTemplateFoldersResponseLinksItemMethod",
]
