# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_action_create_resend_campaigns_request_shortcut_type import (
        CreateActionCreateResendCampaignsRequestShortcutType,
    )
    from .create_action_schedule_campaigns_request_batch_delivery import (
        CreateActionScheduleCampaignsRequestBatchDelivery,
    )
    from .create_action_test_campaigns_request_send_type import CreateActionTestCampaignsRequestSendType
    from .create_campaigns_request_content_type import CreateCampaignsRequestContentType
    from .create_campaigns_request_recipients import CreateCampaignsRequestRecipients
    from .create_campaigns_request_recipients_segment_opts import CreateCampaignsRequestRecipientsSegmentOpts
    from .create_campaigns_request_recipients_segment_opts_match import CreateCampaignsRequestRecipientsSegmentOptsMatch
    from .create_campaigns_request_rss_opts import CreateCampaignsRequestRssOpts
    from .create_campaigns_request_rss_opts_frequency import CreateCampaignsRequestRssOptsFrequency
    from .create_campaigns_request_rss_opts_schedule import CreateCampaignsRequestRssOptsSchedule
    from .create_campaigns_request_rss_opts_schedule_daily_send import CreateCampaignsRequestRssOptsScheduleDailySend
    from .create_campaigns_request_rss_opts_schedule_weekly_send_day import (
        CreateCampaignsRequestRssOptsScheduleWeeklySendDay,
    )
    from .create_campaigns_request_settings import CreateCampaignsRequestSettings
    from .create_campaigns_request_social_card import CreateCampaignsRequestSocialCard
    from .create_campaigns_request_type import CreateCampaignsRequestType
    from .create_campaigns_request_variate_settings import CreateCampaignsRequestVariateSettings
    from .create_campaigns_request_variate_settings_send_times_item import (
        CreateCampaignsRequestVariateSettingsSendTimesItem,
    )
    from .create_campaigns_request_variate_settings_winner_criteria import (
        CreateCampaignsRequestVariateSettingsWinnerCriteria,
    )
    from .create_feedback_campaigns_response import CreateFeedbackCampaignsResponse
    from .list_campaigns_request_sort_dir import ListCampaignsRequestSortDir
    from .list_campaigns_request_sort_field import ListCampaignsRequestSortField
    from .list_campaigns_request_status import ListCampaignsRequestStatus
    from .list_campaigns_request_type import ListCampaignsRequestType
    from .list_campaigns_response import ListCampaignsResponse
    from .list_campaigns_response_links_item import ListCampaignsResponseLinksItem
    from .list_campaigns_response_links_item_method import ListCampaignsResponseLinksItemMethod
    from .list_feedback_campaigns_response import ListFeedbackCampaignsResponse
    from .list_feedback_campaigns_response_feedback_item import ListFeedbackCampaignsResponseFeedbackItem
    from .list_feedback_campaigns_response_feedback_item_links_item import (
        ListFeedbackCampaignsResponseFeedbackItemLinksItem,
    )
    from .list_feedback_campaigns_response_feedback_item_links_item_method import (
        ListFeedbackCampaignsResponseFeedbackItemLinksItemMethod,
    )
    from .list_feedback_campaigns_response_feedback_item_source import ListFeedbackCampaignsResponseFeedbackItemSource
    from .list_feedback_campaigns_response_links_item import ListFeedbackCampaignsResponseLinksItem
    from .list_feedback_campaigns_response_links_item_method import ListFeedbackCampaignsResponseLinksItemMethod
    from .list_send_checklist_campaigns_response import ListSendChecklistCampaignsResponse
    from .list_send_checklist_campaigns_response_items_item import ListSendChecklistCampaignsResponseItemsItem
    from .list_send_checklist_campaigns_response_items_item_type import ListSendChecklistCampaignsResponseItemsItemType
    from .list_send_checklist_campaigns_response_links_item import ListSendChecklistCampaignsResponseLinksItem
    from .list_send_checklist_campaigns_response_links_item_method import (
        ListSendChecklistCampaignsResponseLinksItemMethod,
    )
    from .update_campaigns_request_recipients import UpdateCampaignsRequestRecipients
    from .update_campaigns_request_recipients_segment_opts import UpdateCampaignsRequestRecipientsSegmentOpts
    from .update_campaigns_request_recipients_segment_opts_match import UpdateCampaignsRequestRecipientsSegmentOptsMatch
    from .update_campaigns_request_recipients_segment_opts_saved_segment_id import (
        UpdateCampaignsRequestRecipientsSegmentOptsSavedSegmentId,
    )
    from .update_campaigns_request_rss_opts import UpdateCampaignsRequestRssOpts
    from .update_campaigns_request_rss_opts_frequency import UpdateCampaignsRequestRssOptsFrequency
    from .update_campaigns_request_rss_opts_schedule import UpdateCampaignsRequestRssOptsSchedule
    from .update_campaigns_request_rss_opts_schedule_daily_send import UpdateCampaignsRequestRssOptsScheduleDailySend
    from .update_campaigns_request_rss_opts_schedule_weekly_send_day import (
        UpdateCampaignsRequestRssOptsScheduleWeeklySendDay,
    )
    from .update_campaigns_request_settings import UpdateCampaignsRequestSettings
    from .update_campaigns_request_social_card import UpdateCampaignsRequestSocialCard
    from .update_campaigns_request_variate_settings import UpdateCampaignsRequestVariateSettings
    from .update_campaigns_request_variate_settings_send_times_item import (
        UpdateCampaignsRequestVariateSettingsSendTimesItem,
    )
    from .update_campaigns_request_variate_settings_winner_criteria import (
        UpdateCampaignsRequestVariateSettingsWinnerCriteria,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateActionCreateResendCampaignsRequestShortcutType": ".create_action_create_resend_campaigns_request_shortcut_type",
    "CreateActionScheduleCampaignsRequestBatchDelivery": ".create_action_schedule_campaigns_request_batch_delivery",
    "CreateActionTestCampaignsRequestSendType": ".create_action_test_campaigns_request_send_type",
    "CreateCampaignsRequestContentType": ".create_campaigns_request_content_type",
    "CreateCampaignsRequestRecipients": ".create_campaigns_request_recipients",
    "CreateCampaignsRequestRecipientsSegmentOpts": ".create_campaigns_request_recipients_segment_opts",
    "CreateCampaignsRequestRecipientsSegmentOptsMatch": ".create_campaigns_request_recipients_segment_opts_match",
    "CreateCampaignsRequestRssOpts": ".create_campaigns_request_rss_opts",
    "CreateCampaignsRequestRssOptsFrequency": ".create_campaigns_request_rss_opts_frequency",
    "CreateCampaignsRequestRssOptsSchedule": ".create_campaigns_request_rss_opts_schedule",
    "CreateCampaignsRequestRssOptsScheduleDailySend": ".create_campaigns_request_rss_opts_schedule_daily_send",
    "CreateCampaignsRequestRssOptsScheduleWeeklySendDay": ".create_campaigns_request_rss_opts_schedule_weekly_send_day",
    "CreateCampaignsRequestSettings": ".create_campaigns_request_settings",
    "CreateCampaignsRequestSocialCard": ".create_campaigns_request_social_card",
    "CreateCampaignsRequestType": ".create_campaigns_request_type",
    "CreateCampaignsRequestVariateSettings": ".create_campaigns_request_variate_settings",
    "CreateCampaignsRequestVariateSettingsSendTimesItem": ".create_campaigns_request_variate_settings_send_times_item",
    "CreateCampaignsRequestVariateSettingsWinnerCriteria": ".create_campaigns_request_variate_settings_winner_criteria",
    "CreateFeedbackCampaignsResponse": ".create_feedback_campaigns_response",
    "ListCampaignsRequestSortDir": ".list_campaigns_request_sort_dir",
    "ListCampaignsRequestSortField": ".list_campaigns_request_sort_field",
    "ListCampaignsRequestStatus": ".list_campaigns_request_status",
    "ListCampaignsRequestType": ".list_campaigns_request_type",
    "ListCampaignsResponse": ".list_campaigns_response",
    "ListCampaignsResponseLinksItem": ".list_campaigns_response_links_item",
    "ListCampaignsResponseLinksItemMethod": ".list_campaigns_response_links_item_method",
    "ListFeedbackCampaignsResponse": ".list_feedback_campaigns_response",
    "ListFeedbackCampaignsResponseFeedbackItem": ".list_feedback_campaigns_response_feedback_item",
    "ListFeedbackCampaignsResponseFeedbackItemLinksItem": ".list_feedback_campaigns_response_feedback_item_links_item",
    "ListFeedbackCampaignsResponseFeedbackItemLinksItemMethod": ".list_feedback_campaigns_response_feedback_item_links_item_method",
    "ListFeedbackCampaignsResponseFeedbackItemSource": ".list_feedback_campaigns_response_feedback_item_source",
    "ListFeedbackCampaignsResponseLinksItem": ".list_feedback_campaigns_response_links_item",
    "ListFeedbackCampaignsResponseLinksItemMethod": ".list_feedback_campaigns_response_links_item_method",
    "ListSendChecklistCampaignsResponse": ".list_send_checklist_campaigns_response",
    "ListSendChecklistCampaignsResponseItemsItem": ".list_send_checklist_campaigns_response_items_item",
    "ListSendChecklistCampaignsResponseItemsItemType": ".list_send_checklist_campaigns_response_items_item_type",
    "ListSendChecklistCampaignsResponseLinksItem": ".list_send_checklist_campaigns_response_links_item",
    "ListSendChecklistCampaignsResponseLinksItemMethod": ".list_send_checklist_campaigns_response_links_item_method",
    "UpdateCampaignsRequestRecipients": ".update_campaigns_request_recipients",
    "UpdateCampaignsRequestRecipientsSegmentOpts": ".update_campaigns_request_recipients_segment_opts",
    "UpdateCampaignsRequestRecipientsSegmentOptsMatch": ".update_campaigns_request_recipients_segment_opts_match",
    "UpdateCampaignsRequestRecipientsSegmentOptsSavedSegmentId": ".update_campaigns_request_recipients_segment_opts_saved_segment_id",
    "UpdateCampaignsRequestRssOpts": ".update_campaigns_request_rss_opts",
    "UpdateCampaignsRequestRssOptsFrequency": ".update_campaigns_request_rss_opts_frequency",
    "UpdateCampaignsRequestRssOptsSchedule": ".update_campaigns_request_rss_opts_schedule",
    "UpdateCampaignsRequestRssOptsScheduleDailySend": ".update_campaigns_request_rss_opts_schedule_daily_send",
    "UpdateCampaignsRequestRssOptsScheduleWeeklySendDay": ".update_campaigns_request_rss_opts_schedule_weekly_send_day",
    "UpdateCampaignsRequestSettings": ".update_campaigns_request_settings",
    "UpdateCampaignsRequestSocialCard": ".update_campaigns_request_social_card",
    "UpdateCampaignsRequestVariateSettings": ".update_campaigns_request_variate_settings",
    "UpdateCampaignsRequestVariateSettingsSendTimesItem": ".update_campaigns_request_variate_settings_send_times_item",
    "UpdateCampaignsRequestVariateSettingsWinnerCriteria": ".update_campaigns_request_variate_settings_winner_criteria",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateActionCreateResendCampaignsRequestShortcutType",
    "CreateActionScheduleCampaignsRequestBatchDelivery",
    "CreateActionTestCampaignsRequestSendType",
    "CreateCampaignsRequestContentType",
    "CreateCampaignsRequestRecipients",
    "CreateCampaignsRequestRecipientsSegmentOpts",
    "CreateCampaignsRequestRecipientsSegmentOptsMatch",
    "CreateCampaignsRequestRssOpts",
    "CreateCampaignsRequestRssOptsFrequency",
    "CreateCampaignsRequestRssOptsSchedule",
    "CreateCampaignsRequestRssOptsScheduleDailySend",
    "CreateCampaignsRequestRssOptsScheduleWeeklySendDay",
    "CreateCampaignsRequestSettings",
    "CreateCampaignsRequestSocialCard",
    "CreateCampaignsRequestType",
    "CreateCampaignsRequestVariateSettings",
    "CreateCampaignsRequestVariateSettingsSendTimesItem",
    "CreateCampaignsRequestVariateSettingsWinnerCriteria",
    "CreateFeedbackCampaignsResponse",
    "ListCampaignsRequestSortDir",
    "ListCampaignsRequestSortField",
    "ListCampaignsRequestStatus",
    "ListCampaignsRequestType",
    "ListCampaignsResponse",
    "ListCampaignsResponseLinksItem",
    "ListCampaignsResponseLinksItemMethod",
    "ListFeedbackCampaignsResponse",
    "ListFeedbackCampaignsResponseFeedbackItem",
    "ListFeedbackCampaignsResponseFeedbackItemLinksItem",
    "ListFeedbackCampaignsResponseFeedbackItemLinksItemMethod",
    "ListFeedbackCampaignsResponseFeedbackItemSource",
    "ListFeedbackCampaignsResponseLinksItem",
    "ListFeedbackCampaignsResponseLinksItemMethod",
    "ListSendChecklistCampaignsResponse",
    "ListSendChecklistCampaignsResponseItemsItem",
    "ListSendChecklistCampaignsResponseItemsItemType",
    "ListSendChecklistCampaignsResponseLinksItem",
    "ListSendChecklistCampaignsResponseLinksItemMethod",
    "UpdateCampaignsRequestRecipients",
    "UpdateCampaignsRequestRecipientsSegmentOpts",
    "UpdateCampaignsRequestRecipientsSegmentOptsMatch",
    "UpdateCampaignsRequestRecipientsSegmentOptsSavedSegmentId",
    "UpdateCampaignsRequestRssOpts",
    "UpdateCampaignsRequestRssOptsFrequency",
    "UpdateCampaignsRequestRssOptsSchedule",
    "UpdateCampaignsRequestRssOptsScheduleDailySend",
    "UpdateCampaignsRequestRssOptsScheduleWeeklySendDay",
    "UpdateCampaignsRequestSettings",
    "UpdateCampaignsRequestSocialCard",
    "UpdateCampaignsRequestVariateSettings",
    "UpdateCampaignsRequestVariateSettingsSendTimesItem",
    "UpdateCampaignsRequestVariateSettingsWinnerCriteria",
]
