# This file was auto-generated by Fern from our API Definition.

import typing

ListSendChecklistCampaignsResponseItemsItemType = typing.Union[
    typing.Literal["success", "warning", "error"], typing.Any
]
