# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawSearchCampaignsClient, RawSearchCampaignsClient
from .types.list_search_campaigns_response import ListSearchCampaignsResponse


class SearchCampaignsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSearchCampaignsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSearchCampaignsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSearchCampaignsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        query: str,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSearchCampaignsResponse:
        """
        Search all campaigns for the specified query terms.

        Parameters
        ----------
        query : str
            The search query used to filter results.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSearchCampaignsResponse


        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.search_campaigns.list(
            query="query",
        )
        """
        _response = self._raw_client.list(
            query=query, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data


class AsyncSearchCampaignsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSearchCampaignsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSearchCampaignsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSearchCampaignsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        query: str,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSearchCampaignsResponse:
        """
        Search all campaigns for the specified query terms.

        Parameters
        ----------
        query : str
            The search query used to filter results.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSearchCampaignsResponse


        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.search_campaigns.list(
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            query=query, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data
