# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.connected_site import ConnectedSite
from .raw_client import AsyncRawConnectedSitesClient, RawConnectedSitesClient
from .types.list_connected_sites_response import ListConnectedSitesResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ConnectedSitesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConnectedSitesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConnectedSitesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConnectedSitesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ConnectedSite, ListConnectedSitesResponse]:
        """
        Get all connected sites in an account.

        Parameters
        ----------
        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ConnectedSite, ListConnectedSitesResponse]


        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        response = client.connected_sites.list()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            fields=fields, exclude_fields=exclude_fields, count=count, offset=offset, request_options=request_options
        )

    def create(
        self, *, domain: str, foreign_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ConnectedSite:
        """
        Create a new Mailchimp connected site.

        Parameters
        ----------
        domain : str
            The connected site domain.

        foreign_id : str
            The unique identifier for the site.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectedSite


        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.connected_sites.create(
            domain="example.com",
            foreign_id="MC001",
        )
        """
        _response = self._raw_client.create(domain=domain, foreign_id=foreign_id, request_options=request_options)
        return _response.data

    def get(
        self,
        connected_site_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConnectedSite:
        """
        Get information about a specific connected site.

        Parameters
        ----------
        connected_site_id : str
            The unique identifier for the site.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectedSite


        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.connected_sites.get(
            connected_site_id="connected_site_id",
        )
        """
        _response = self._raw_client.get(
            connected_site_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    def delete(self, connected_site_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove a connected site from your Mailchimp account.

        Parameters
        ----------
        connected_site_id : str
            The unique identifier for the site.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.connected_sites.delete(
            connected_site_id="connected_site_id",
        )
        """
        _response = self._raw_client.delete(connected_site_id, request_options=request_options)
        return _response.data

    def create_action_verify_script_installation(
        self, connected_site_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Verify that the connected sites script has been installed, either via the script URL or fragment.

        Parameters
        ----------
        connected_site_id : str
            The unique identifier for the site.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.connected_sites.create_action_verify_script_installation(
            connected_site_id="connected_site_id",
        )
        """
        _response = self._raw_client.create_action_verify_script_installation(
            connected_site_id, request_options=request_options
        )
        return _response.data


class AsyncConnectedSitesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConnectedSitesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConnectedSitesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConnectedSitesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ConnectedSite, ListConnectedSitesResponse]:
        """
        Get all connected sites in an account.

        Parameters
        ----------
        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ConnectedSite, ListConnectedSitesResponse]


        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.connected_sites.list()
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            fields=fields, exclude_fields=exclude_fields, count=count, offset=offset, request_options=request_options
        )

    async def create(
        self, *, domain: str, foreign_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ConnectedSite:
        """
        Create a new Mailchimp connected site.

        Parameters
        ----------
        domain : str
            The connected site domain.

        foreign_id : str
            The unique identifier for the site.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectedSite


        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.connected_sites.create(
                domain="example.com",
                foreign_id="MC001",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(domain=domain, foreign_id=foreign_id, request_options=request_options)
        return _response.data

    async def get(
        self,
        connected_site_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConnectedSite:
        """
        Get information about a specific connected site.

        Parameters
        ----------
        connected_site_id : str
            The unique identifier for the site.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectedSite


        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.connected_sites.get(
                connected_site_id="connected_site_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(
            connected_site_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    async def delete(self, connected_site_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove a connected site from your Mailchimp account.

        Parameters
        ----------
        connected_site_id : str
            The unique identifier for the site.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.connected_sites.delete(
                connected_site_id="connected_site_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(connected_site_id, request_options=request_options)
        return _response.data

    async def create_action_verify_script_installation(
        self, connected_site_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Verify that the connected sites script has been installed, either via the script URL or fragment.

        Parameters
        ----------
        connected_site_id : str
            The unique identifier for the site.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.connected_sites.create_action_verify_script_installation(
                connected_site_id="connected_site_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_action_verify_script_installation(
            connected_site_id, request_options=request_options
        )
        return _response.data
