# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.landing_page_report import LandingPageReport
from ..types.reporting_facebook_ad import ReportingFacebookAd
from ..types.survey_question_report import SurveyQuestionReport
from .raw_client import AsyncRawReportingClient, RawReportingClient
from .types.get_survey_reporting_response import GetSurveyReportingResponse
from .types.get_survey_respons_reporting_response import GetSurveyResponsReportingResponse
from .types.list_facebook_ad_ecommerce_product_activity_reporting_request_sort_field import (
    ListFacebookAdEcommerceProductActivityReportingRequestSortField,
)
from .types.list_facebook_ad_ecommerce_product_activity_reporting_response import (
    ListFacebookAdEcommerceProductActivityReportingResponse,
)
from .types.list_facebook_ad_ecommerce_product_activity_reporting_response_products_item import (
    ListFacebookAdEcommerceProductActivityReportingResponseProductsItem,
)
from .types.list_facebook_ads_reporting_request_sort_dir import ListFacebookAdsReportingRequestSortDir
from .types.list_facebook_ads_reporting_request_sort_field import ListFacebookAdsReportingRequestSortField
from .types.list_facebook_ads_reporting_response import ListFacebookAdsReportingResponse
from .types.list_landing_pages_reporting_response import ListLandingPagesReportingResponse
from .types.list_reporting_response_item import ListReportingResponseItem
from .types.list_survey_question_answers_reporting_request_respondent_familiarity_is import (
    ListSurveyQuestionAnswersReportingRequestRespondentFamiliarityIs,
)
from .types.list_survey_question_answers_reporting_response import ListSurveyQuestionAnswersReportingResponse
from .types.list_survey_questions_reporting_response import ListSurveyQuestionsReportingResponse
from .types.list_survey_responses_reporting_request_respondent_familiarity_is import (
    ListSurveyResponsesReportingRequestRespondentFamiliarityIs,
)
from .types.list_survey_responses_reporting_response import ListSurveyResponsesReportingResponse
from .types.list_surveys_reporting_response import ListSurveysReportingResponse
from .types.list_surveys_reporting_response_surveys_item import ListSurveysReportingResponseSurveysItem


class ReportingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawReportingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawReportingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawReportingClient
        """
        return self._raw_client

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListReportingResponseItem]:
        """
        Get information about the reporting endpoint's resources.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListReportingResponseItem]
            Available resources under reporting endpoint

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.reporting.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def list_facebook_ads(
        self,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        sort_field: typing.Optional[ListFacebookAdsReportingRequestSortField] = None,
        sort_dir: typing.Optional[ListFacebookAdsReportingRequestSortDir] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ReportingFacebookAd, ListFacebookAdsReportingResponse]:
        """
        Get reports of Facebook ads.

        Parameters
        ----------
        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        sort_field : typing.Optional[ListFacebookAdsReportingRequestSortField]
            Returns files sorted by the specified field.

        sort_dir : typing.Optional[ListFacebookAdsReportingRequestSortDir]
            Determines the order direction for sorted results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ReportingFacebookAd, ListFacebookAdsReportingResponse]
            List of Facebook Ad Report Instances

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        response = client.reporting.list_facebook_ads()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_facebook_ads(
            fields=fields,
            exclude_fields=exclude_fields,
            count=count,
            offset=offset,
            sort_field=sort_field,
            sort_dir=sort_dir,
            request_options=request_options,
        )

    def get_facebook_ad(
        self,
        outreach_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ReportingFacebookAd:
        """
        Get report of a Facebook ad.

        Parameters
        ----------
        outreach_id : str
            The outreach id.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReportingFacebookAd
            Facebook Ad report Instance

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.reporting.get_facebook_ad(
            outreach_id="outreach_id",
        )
        """
        _response = self._raw_client.get_facebook_ad(
            outreach_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    def list_facebook_ad_ecommerce_product_activity(
        self,
        outreach_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        sort_field: typing.Optional[ListFacebookAdEcommerceProductActivityReportingRequestSortField] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[
        ListFacebookAdEcommerceProductActivityReportingResponseProductsItem,
        ListFacebookAdEcommerceProductActivityReportingResponse,
    ]:
        """
        Get breakdown of product activity for an outreach.

        Parameters
        ----------
        outreach_id : str
            The outreach id.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        sort_field : typing.Optional[ListFacebookAdEcommerceProductActivityReportingRequestSortField]
            Returns files sorted by the specified field.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ListFacebookAdEcommerceProductActivityReportingResponseProductsItem, ListFacebookAdEcommerceProductActivityReportingResponse]
            Ecommerce Product Activity Instance

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        response = client.reporting.list_facebook_ad_ecommerce_product_activity(
            outreach_id="outreach_id",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_facebook_ad_ecommerce_product_activity(
            outreach_id,
            fields=fields,
            exclude_fields=exclude_fields,
            count=count,
            offset=offset,
            sort_field=sort_field,
            request_options=request_options,
        )

    def list_landing_pages(
        self,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[LandingPageReport, ListLandingPagesReportingResponse]:
        """
        Get reports of landing pages.

        Parameters
        ----------
        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[LandingPageReport, ListLandingPagesReportingResponse]
            List of Landing Page Report Instances

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        response = client.reporting.list_landing_pages()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_landing_pages(
            fields=fields, exclude_fields=exclude_fields, count=count, offset=offset, request_options=request_options
        )

    def get_landing_page(
        self,
        outreach_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LandingPageReport:
        """
        Get report of a landing page.

        Parameters
        ----------
        outreach_id : str
            The outreach id.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LandingPageReport
            Landing Page Report Instance

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.reporting.get_landing_page(
            outreach_id="outreach_id",
        )
        """
        _response = self._raw_client.get_landing_page(
            outreach_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    def list_surveys(
        self,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ListSurveysReportingResponseSurveysItem, ListSurveysReportingResponse]:
        """
        Get reports for surveys.

        Parameters
        ----------
        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ListSurveysReportingResponseSurveysItem, ListSurveysReportingResponse]
            List of Survey Report Instances

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        response = client.reporting.list_surveys()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_surveys(
            fields=fields, exclude_fields=exclude_fields, count=count, offset=offset, request_options=request_options
        )

    def get_survey(
        self,
        survey_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetSurveyReportingResponse:
        """
        Get report for a survey.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSurveyReportingResponse
            Survey Report Instance

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.reporting.get_survey(
            survey_id="survey_id",
        )
        """
        _response = self._raw_client.get_survey(
            survey_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    def list_survey_questions(
        self,
        survey_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSurveyQuestionsReportingResponse:
        """
        Get reports for survey questions.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSurveyQuestionsReportingResponse
            List of Survey Question Report Instances

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.reporting.list_survey_questions(
            survey_id="survey_id",
        )
        """
        _response = self._raw_client.list_survey_questions(
            survey_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    def get_survey_question(
        self,
        survey_id: str,
        question_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SurveyQuestionReport:
        """
        Get report for a survey question.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        question_id : str
            The ID of the survey question.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SurveyQuestionReport
            Survey Question Report Instance

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.reporting.get_survey_question(
            survey_id="survey_id",
            question_id="question_id",
        )
        """
        _response = self._raw_client.get_survey_question(
            survey_id, question_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    def list_survey_question_answers(
        self,
        survey_id: str,
        question_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        respondent_familiarity_is: typing.Optional[
            ListSurveyQuestionAnswersReportingRequestRespondentFamiliarityIs
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSurveyQuestionAnswersReportingResponse:
        """
        Get answers for a survey question.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        question_id : str
            The ID of the survey question.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        respondent_familiarity_is : typing.Optional[ListSurveyQuestionAnswersReportingRequestRespondentFamiliarityIs]
            Filter survey responses by familiarity of the respondents.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSurveyQuestionAnswersReportingResponse
            List of Survey Question Answers

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.reporting.list_survey_question_answers(
            survey_id="survey_id",
            question_id="question_id",
        )
        """
        _response = self._raw_client.list_survey_question_answers(
            survey_id,
            question_id,
            fields=fields,
            exclude_fields=exclude_fields,
            respondent_familiarity_is=respondent_familiarity_is,
            request_options=request_options,
        )
        return _response.data

    def list_survey_responses(
        self,
        survey_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        answered_question: typing.Optional[int] = None,
        chose_answer: typing.Optional[str] = None,
        respondent_familiarity_is: typing.Optional[ListSurveyResponsesReportingRequestRespondentFamiliarityIs] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSurveyResponsesReportingResponse:
        """
        Get responses to a survey.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        answered_question : typing.Optional[int]
            The ID of the question that was answered.

        chose_answer : typing.Optional[str]
            The ID of the option chosen to filter responses on.

        respondent_familiarity_is : typing.Optional[ListSurveyResponsesReportingRequestRespondentFamiliarityIs]
            Filter survey responses by familiarity of the respondents.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSurveyResponsesReportingResponse
            List of survey responses

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.reporting.list_survey_responses(
            survey_id="survey_id",
        )
        """
        _response = self._raw_client.list_survey_responses(
            survey_id,
            fields=fields,
            exclude_fields=exclude_fields,
            answered_question=answered_question,
            chose_answer=chose_answer,
            respondent_familiarity_is=respondent_familiarity_is,
            request_options=request_options,
        )
        return _response.data

    def get_survey_respons(
        self, survey_id: str, response_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSurveyResponsReportingResponse:
        """
        Get a single survey response.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        response_id : str
            The ID of the survey response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSurveyResponsReportingResponse
            Get a single survey response.

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.reporting.get_survey_respons(
            survey_id="survey_id",
            response_id="response_id",
        )
        """
        _response = self._raw_client.get_survey_respons(survey_id, response_id, request_options=request_options)
        return _response.data


class AsyncReportingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawReportingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawReportingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawReportingClient
        """
        return self._raw_client

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListReportingResponseItem]:
        """
        Get information about the reporting endpoint's resources.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListReportingResponseItem]
            Available resources under reporting endpoint

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reporting.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def list_facebook_ads(
        self,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        sort_field: typing.Optional[ListFacebookAdsReportingRequestSortField] = None,
        sort_dir: typing.Optional[ListFacebookAdsReportingRequestSortDir] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ReportingFacebookAd, ListFacebookAdsReportingResponse]:
        """
        Get reports of Facebook ads.

        Parameters
        ----------
        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        sort_field : typing.Optional[ListFacebookAdsReportingRequestSortField]
            Returns files sorted by the specified field.

        sort_dir : typing.Optional[ListFacebookAdsReportingRequestSortDir]
            Determines the order direction for sorted results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ReportingFacebookAd, ListFacebookAdsReportingResponse]
            List of Facebook Ad Report Instances

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.reporting.list_facebook_ads()
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_facebook_ads(
            fields=fields,
            exclude_fields=exclude_fields,
            count=count,
            offset=offset,
            sort_field=sort_field,
            sort_dir=sort_dir,
            request_options=request_options,
        )

    async def get_facebook_ad(
        self,
        outreach_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ReportingFacebookAd:
        """
        Get report of a Facebook ad.

        Parameters
        ----------
        outreach_id : str
            The outreach id.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReportingFacebookAd
            Facebook Ad report Instance

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reporting.get_facebook_ad(
                outreach_id="outreach_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_facebook_ad(
            outreach_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    async def list_facebook_ad_ecommerce_product_activity(
        self,
        outreach_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        sort_field: typing.Optional[ListFacebookAdEcommerceProductActivityReportingRequestSortField] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[
        ListFacebookAdEcommerceProductActivityReportingResponseProductsItem,
        ListFacebookAdEcommerceProductActivityReportingResponse,
    ]:
        """
        Get breakdown of product activity for an outreach.

        Parameters
        ----------
        outreach_id : str
            The outreach id.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        sort_field : typing.Optional[ListFacebookAdEcommerceProductActivityReportingRequestSortField]
            Returns files sorted by the specified field.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ListFacebookAdEcommerceProductActivityReportingResponseProductsItem, ListFacebookAdEcommerceProductActivityReportingResponse]
            Ecommerce Product Activity Instance

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = (
                await client.reporting.list_facebook_ad_ecommerce_product_activity(
                    outreach_id="outreach_id",
                )
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_facebook_ad_ecommerce_product_activity(
            outreach_id,
            fields=fields,
            exclude_fields=exclude_fields,
            count=count,
            offset=offset,
            sort_field=sort_field,
            request_options=request_options,
        )

    async def list_landing_pages(
        self,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[LandingPageReport, ListLandingPagesReportingResponse]:
        """
        Get reports of landing pages.

        Parameters
        ----------
        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[LandingPageReport, ListLandingPagesReportingResponse]
            List of Landing Page Report Instances

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.reporting.list_landing_pages()
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_landing_pages(
            fields=fields, exclude_fields=exclude_fields, count=count, offset=offset, request_options=request_options
        )

    async def get_landing_page(
        self,
        outreach_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LandingPageReport:
        """
        Get report of a landing page.

        Parameters
        ----------
        outreach_id : str
            The outreach id.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LandingPageReport
            Landing Page Report Instance

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reporting.get_landing_page(
                outreach_id="outreach_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_landing_page(
            outreach_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    async def list_surveys(
        self,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ListSurveysReportingResponseSurveysItem, ListSurveysReportingResponse]:
        """
        Get reports for surveys.

        Parameters
        ----------
        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ListSurveysReportingResponseSurveysItem, ListSurveysReportingResponse]
            List of Survey Report Instances

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.reporting.list_surveys()
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_surveys(
            fields=fields, exclude_fields=exclude_fields, count=count, offset=offset, request_options=request_options
        )

    async def get_survey(
        self,
        survey_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetSurveyReportingResponse:
        """
        Get report for a survey.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSurveyReportingResponse
            Survey Report Instance

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reporting.get_survey(
                survey_id="survey_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_survey(
            survey_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    async def list_survey_questions(
        self,
        survey_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSurveyQuestionsReportingResponse:
        """
        Get reports for survey questions.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSurveyQuestionsReportingResponse
            List of Survey Question Report Instances

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reporting.list_survey_questions(
                survey_id="survey_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_survey_questions(
            survey_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    async def get_survey_question(
        self,
        survey_id: str,
        question_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SurveyQuestionReport:
        """
        Get report for a survey question.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        question_id : str
            The ID of the survey question.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SurveyQuestionReport
            Survey Question Report Instance

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reporting.get_survey_question(
                survey_id="survey_id",
                question_id="question_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_survey_question(
            survey_id, question_id, fields=fields, exclude_fields=exclude_fields, request_options=request_options
        )
        return _response.data

    async def list_survey_question_answers(
        self,
        survey_id: str,
        question_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        respondent_familiarity_is: typing.Optional[
            ListSurveyQuestionAnswersReportingRequestRespondentFamiliarityIs
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSurveyQuestionAnswersReportingResponse:
        """
        Get answers for a survey question.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        question_id : str
            The ID of the survey question.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        respondent_familiarity_is : typing.Optional[ListSurveyQuestionAnswersReportingRequestRespondentFamiliarityIs]
            Filter survey responses by familiarity of the respondents.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSurveyQuestionAnswersReportingResponse
            List of Survey Question Answers

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reporting.list_survey_question_answers(
                survey_id="survey_id",
                question_id="question_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_survey_question_answers(
            survey_id,
            question_id,
            fields=fields,
            exclude_fields=exclude_fields,
            respondent_familiarity_is=respondent_familiarity_is,
            request_options=request_options,
        )
        return _response.data

    async def list_survey_responses(
        self,
        survey_id: str,
        *,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        exclude_fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        answered_question: typing.Optional[int] = None,
        chose_answer: typing.Optional[str] = None,
        respondent_familiarity_is: typing.Optional[ListSurveyResponsesReportingRequestRespondentFamiliarityIs] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSurveyResponsesReportingResponse:
        """
        Get responses to a survey.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

        exclude_fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

        answered_question : typing.Optional[int]
            The ID of the question that was answered.

        chose_answer : typing.Optional[str]
            The ID of the option chosen to filter responses on.

        respondent_familiarity_is : typing.Optional[ListSurveyResponsesReportingRequestRespondentFamiliarityIs]
            Filter survey responses by familiarity of the respondents.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSurveyResponsesReportingResponse
            List of survey responses

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reporting.list_survey_responses(
                survey_id="survey_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_survey_responses(
            survey_id,
            fields=fields,
            exclude_fields=exclude_fields,
            answered_question=answered_question,
            chose_answer=chose_answer,
            respondent_familiarity_is=respondent_familiarity_is,
            request_options=request_options,
        )
        return _response.data

    async def get_survey_respons(
        self, survey_id: str, response_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSurveyResponsReportingResponse:
        """
        Get a single survey response.

        Parameters
        ----------
        survey_id : str
            The ID of the survey.

        response_id : str
            The ID of the survey response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSurveyResponsReportingResponse
            Get a single survey response.

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reporting.get_survey_respons(
                survey_id="survey_id",
                response_id="response_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_survey_respons(survey_id, response_id, request_options=request_options)
        return _response.data
