# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_store_cart_ecommerce_request_id import CreateStoreCartEcommerceRequestId
    from .create_store_cart_ecommerce_request_lines_item import CreateStoreCartEcommerceRequestLinesItem
    from .create_store_cart_ecommerce_request_lines_item_price import CreateStoreCartEcommerceRequestLinesItemPrice
    from .create_store_cart_ecommerce_request_order_total import CreateStoreCartEcommerceRequestOrderTotal
    from .create_store_cart_ecommerce_request_tax_total import CreateStoreCartEcommerceRequestTaxTotal
    from .create_store_cart_line_ecommerce_request_price import CreateStoreCartLineEcommerceRequestPrice
    from .create_store_customer_ecommerce_request_address import CreateStoreCustomerEcommerceRequestAddress
    from .create_store_customer_ecommerce_request_total_spent import CreateStoreCustomerEcommerceRequestTotalSpent
    from .create_store_ecommerce_request_address import CreateStoreEcommerceRequestAddress
    from .create_store_ecommerce_request_address_latitude import CreateStoreEcommerceRequestAddressLatitude
    from .create_store_ecommerce_request_address_longitude import CreateStoreEcommerceRequestAddressLongitude
    from .create_store_order_ecommerce_request_billing_address import CreateStoreOrderEcommerceRequestBillingAddress
    from .create_store_order_ecommerce_request_billing_address_latitude import (
        CreateStoreOrderEcommerceRequestBillingAddressLatitude,
    )
    from .create_store_order_ecommerce_request_billing_address_longitude import (
        CreateStoreOrderEcommerceRequestBillingAddressLongitude,
    )
    from .create_store_order_ecommerce_request_cart_id import CreateStoreOrderEcommerceRequestCartId
    from .create_store_order_ecommerce_request_discount_total import CreateStoreOrderEcommerceRequestDiscountTotal
    from .create_store_order_ecommerce_request_lines_item import CreateStoreOrderEcommerceRequestLinesItem
    from .create_store_order_ecommerce_request_lines_item_discount import (
        CreateStoreOrderEcommerceRequestLinesItemDiscount,
    )
    from .create_store_order_ecommerce_request_lines_item_price import CreateStoreOrderEcommerceRequestLinesItemPrice
    from .create_store_order_ecommerce_request_order_total import CreateStoreOrderEcommerceRequestOrderTotal
    from .create_store_order_ecommerce_request_outreach import CreateStoreOrderEcommerceRequestOutreach
    from .create_store_order_ecommerce_request_promos_item import CreateStoreOrderEcommerceRequestPromosItem
    from .create_store_order_ecommerce_request_promos_item_amount_discounted import (
        CreateStoreOrderEcommerceRequestPromosItemAmountDiscounted,
    )
    from .create_store_order_ecommerce_request_promos_item_type import CreateStoreOrderEcommerceRequestPromosItemType
    from .create_store_order_ecommerce_request_shipping_address import CreateStoreOrderEcommerceRequestShippingAddress
    from .create_store_order_ecommerce_request_shipping_address_latitude import (
        CreateStoreOrderEcommerceRequestShippingAddressLatitude,
    )
    from .create_store_order_ecommerce_request_shipping_address_longitude import (
        CreateStoreOrderEcommerceRequestShippingAddressLongitude,
    )
    from .create_store_order_ecommerce_request_shipping_total import CreateStoreOrderEcommerceRequestShippingTotal
    from .create_store_order_ecommerce_request_tax_total import CreateStoreOrderEcommerceRequestTaxTotal
    from .create_store_order_ecommerce_request_tracking_code import CreateStoreOrderEcommerceRequestTrackingCode
    from .create_store_order_line_ecommerce_request_discount import CreateStoreOrderLineEcommerceRequestDiscount
    from .create_store_order_line_ecommerce_request_price import CreateStoreOrderLineEcommerceRequestPrice
    from .create_store_product_image_ecommerce_request_variant_ids_item import (
        CreateStoreProductImageEcommerceRequestVariantIdsItem,
    )
    from .create_store_product_image_ecommerce_response import CreateStoreProductImageEcommerceResponse
    from .create_store_product_image_ecommerce_response_links_item import (
        CreateStoreProductImageEcommerceResponseLinksItem,
    )
    from .create_store_product_image_ecommerce_response_links_item_method import (
        CreateStoreProductImageEcommerceResponseLinksItemMethod,
    )
    from .create_store_product_variant_ecommerce_request_id import CreateStoreProductVariantEcommerceRequestId
    from .create_store_product_variant_ecommerce_request_price import CreateStoreProductVariantEcommerceRequestPrice
    from .create_store_promo_rule_ecommerce_request_amount import CreateStorePromoRuleEcommerceRequestAmount
    from .create_store_promo_rule_ecommerce_request_ends_at import CreateStorePromoRuleEcommerceRequestEndsAt
    from .create_store_promo_rule_ecommerce_request_ends_at_one import CreateStorePromoRuleEcommerceRequestEndsAtOne
    from .create_store_promo_rule_ecommerce_request_ends_at_zero import CreateStorePromoRuleEcommerceRequestEndsAtZero
    from .create_store_promo_rule_ecommerce_request_starts_at import CreateStorePromoRuleEcommerceRequestStartsAt
    from .create_store_promo_rule_ecommerce_request_starts_at_one import CreateStorePromoRuleEcommerceRequestStartsAtOne
    from .create_store_promo_rule_ecommerce_request_starts_at_zero import (
        CreateStorePromoRuleEcommerceRequestStartsAtZero,
    )
    from .create_store_promo_rule_ecommerce_request_target import CreateStorePromoRuleEcommerceRequestTarget
    from .create_store_promo_rule_ecommerce_request_type import CreateStorePromoRuleEcommerceRequestType
    from .get_store_product_image_ecommerce_response import GetStoreProductImageEcommerceResponse
    from .get_store_product_image_ecommerce_response_links_item import GetStoreProductImageEcommerceResponseLinksItem
    from .get_store_product_image_ecommerce_response_links_item_method import (
        GetStoreProductImageEcommerceResponseLinksItemMethod,
    )
    from .list_ecommerce_response import ListEcommerceResponse
    from .list_ecommerce_response_links_item import ListEcommerceResponseLinksItem
    from .list_ecommerce_response_links_item_method import ListEcommerceResponseLinksItemMethod
    from .list_orders_ecommerce_response import ListOrdersEcommerceResponse
    from .list_orders_ecommerce_response_links_item import ListOrdersEcommerceResponseLinksItem
    from .list_orders_ecommerce_response_links_item_method import ListOrdersEcommerceResponseLinksItemMethod
    from .list_store_cart_lines_ecommerce_response import ListStoreCartLinesEcommerceResponse
    from .list_store_cart_lines_ecommerce_response_links_item import ListStoreCartLinesEcommerceResponseLinksItem
    from .list_store_cart_lines_ecommerce_response_links_item_method import (
        ListStoreCartLinesEcommerceResponseLinksItemMethod,
    )
    from .list_store_carts_ecommerce_response import ListStoreCartsEcommerceResponse
    from .list_store_carts_ecommerce_response_links_item import ListStoreCartsEcommerceResponseLinksItem
    from .list_store_carts_ecommerce_response_links_item_method import ListStoreCartsEcommerceResponseLinksItemMethod
    from .list_store_customers_ecommerce_response import ListStoreCustomersEcommerceResponse
    from .list_store_customers_ecommerce_response_links_item import ListStoreCustomersEcommerceResponseLinksItem
    from .list_store_customers_ecommerce_response_links_item_method import (
        ListStoreCustomersEcommerceResponseLinksItemMethod,
    )
    from .list_store_order_lines_ecommerce_response import ListStoreOrderLinesEcommerceResponse
    from .list_store_order_lines_ecommerce_response_links_item import ListStoreOrderLinesEcommerceResponseLinksItem
    from .list_store_order_lines_ecommerce_response_links_item_method import (
        ListStoreOrderLinesEcommerceResponseLinksItemMethod,
    )
    from .list_store_orders_ecommerce_response import ListStoreOrdersEcommerceResponse
    from .list_store_orders_ecommerce_response_links_item import ListStoreOrdersEcommerceResponseLinksItem
    from .list_store_orders_ecommerce_response_links_item_method import ListStoreOrdersEcommerceResponseLinksItemMethod
    from .list_store_product_images_ecommerce_response import ListStoreProductImagesEcommerceResponse
    from .list_store_product_images_ecommerce_response_images_item import (
        ListStoreProductImagesEcommerceResponseImagesItem,
    )
    from .list_store_product_images_ecommerce_response_images_item_links_item import (
        ListStoreProductImagesEcommerceResponseImagesItemLinksItem,
    )
    from .list_store_product_images_ecommerce_response_images_item_links_item_method import (
        ListStoreProductImagesEcommerceResponseImagesItemLinksItemMethod,
    )
    from .list_store_product_images_ecommerce_response_links_item import (
        ListStoreProductImagesEcommerceResponseLinksItem,
    )
    from .list_store_product_images_ecommerce_response_links_item_method import (
        ListStoreProductImagesEcommerceResponseLinksItemMethod,
    )
    from .list_store_product_variants_ecommerce_response import ListStoreProductVariantsEcommerceResponse
    from .list_store_product_variants_ecommerce_response_links_item import (
        ListStoreProductVariantsEcommerceResponseLinksItem,
    )
    from .list_store_product_variants_ecommerce_response_links_item_method import (
        ListStoreProductVariantsEcommerceResponseLinksItemMethod,
    )
    from .list_store_products_ecommerce_response import ListStoreProductsEcommerceResponse
    from .list_store_products_ecommerce_response_links_item import ListStoreProductsEcommerceResponseLinksItem
    from .list_store_products_ecommerce_response_links_item_method import (
        ListStoreProductsEcommerceResponseLinksItemMethod,
    )
    from .list_store_promo_rule_promo_codes_ecommerce_response import ListStorePromoRulePromoCodesEcommerceResponse
    from .list_store_promo_rule_promo_codes_ecommerce_response_links_item import (
        ListStorePromoRulePromoCodesEcommerceResponseLinksItem,
    )
    from .list_store_promo_rule_promo_codes_ecommerce_response_links_item_method import (
        ListStorePromoRulePromoCodesEcommerceResponseLinksItemMethod,
    )
    from .list_store_promo_rules_ecommerce_response import ListStorePromoRulesEcommerceResponse
    from .list_store_promo_rules_ecommerce_response_links_item import ListStorePromoRulesEcommerceResponseLinksItem
    from .list_store_promo_rules_ecommerce_response_links_item_method import (
        ListStorePromoRulesEcommerceResponseLinksItemMethod,
    )
    from .list_stores_ecommerce_response import ListStoresEcommerceResponse
    from .list_stores_ecommerce_response_links_item import ListStoresEcommerceResponseLinksItem
    from .list_stores_ecommerce_response_links_item_method import ListStoresEcommerceResponseLinksItemMethod
    from .update_store_cart_ecommerce_request_id import UpdateStoreCartEcommerceRequestId
    from .update_store_cart_ecommerce_request_lines_item import UpdateStoreCartEcommerceRequestLinesItem
    from .update_store_cart_ecommerce_request_lines_item_price import UpdateStoreCartEcommerceRequestLinesItemPrice
    from .update_store_cart_ecommerce_request_order_total import UpdateStoreCartEcommerceRequestOrderTotal
    from .update_store_cart_ecommerce_request_tax_total import UpdateStoreCartEcommerceRequestTaxTotal
    from .update_store_cart_line_ecommerce_request_price import UpdateStoreCartLineEcommerceRequestPrice
    from .update_store_ecommerce_request_address import UpdateStoreEcommerceRequestAddress
    from .update_store_ecommerce_request_address_latitude import UpdateStoreEcommerceRequestAddressLatitude
    from .update_store_ecommerce_request_address_longitude import UpdateStoreEcommerceRequestAddressLongitude
    from .update_store_order_ecommerce_request_billing_address import UpdateStoreOrderEcommerceRequestBillingAddress
    from .update_store_order_ecommerce_request_billing_address_latitude import (
        UpdateStoreOrderEcommerceRequestBillingAddressLatitude,
    )
    from .update_store_order_ecommerce_request_billing_address_longitude import (
        UpdateStoreOrderEcommerceRequestBillingAddressLongitude,
    )
    from .update_store_order_ecommerce_request_cart_id import UpdateStoreOrderEcommerceRequestCartId
    from .update_store_order_ecommerce_request_discount_total import UpdateStoreOrderEcommerceRequestDiscountTotal
    from .update_store_order_ecommerce_request_lines_item import UpdateStoreOrderEcommerceRequestLinesItem
    from .update_store_order_ecommerce_request_lines_item_discount import (
        UpdateStoreOrderEcommerceRequestLinesItemDiscount,
    )
    from .update_store_order_ecommerce_request_lines_item_price import UpdateStoreOrderEcommerceRequestLinesItemPrice
    from .update_store_order_ecommerce_request_order_total import UpdateStoreOrderEcommerceRequestOrderTotal
    from .update_store_order_ecommerce_request_outreach import UpdateStoreOrderEcommerceRequestOutreach
    from .update_store_order_ecommerce_request_promos_item import UpdateStoreOrderEcommerceRequestPromosItem
    from .update_store_order_ecommerce_request_promos_item_amount_discounted import (
        UpdateStoreOrderEcommerceRequestPromosItemAmountDiscounted,
    )
    from .update_store_order_ecommerce_request_promos_item_type import UpdateStoreOrderEcommerceRequestPromosItemType
    from .update_store_order_ecommerce_request_shipping_address import UpdateStoreOrderEcommerceRequestShippingAddress
    from .update_store_order_ecommerce_request_shipping_address_latitude import (
        UpdateStoreOrderEcommerceRequestShippingAddressLatitude,
    )
    from .update_store_order_ecommerce_request_shipping_address_longitude import (
        UpdateStoreOrderEcommerceRequestShippingAddressLongitude,
    )
    from .update_store_order_ecommerce_request_shipping_total import UpdateStoreOrderEcommerceRequestShippingTotal
    from .update_store_order_ecommerce_request_tax_total import UpdateStoreOrderEcommerceRequestTaxTotal
    from .update_store_order_ecommerce_request_tracking_code import UpdateStoreOrderEcommerceRequestTrackingCode
    from .update_store_order_line_ecommerce_request_discount import UpdateStoreOrderLineEcommerceRequestDiscount
    from .update_store_order_line_ecommerce_request_price import UpdateStoreOrderLineEcommerceRequestPrice
    from .update_store_product_ecommerce_request_id import UpdateStoreProductEcommerceRequestId
    from .update_store_product_ecommerce_request_images_item import UpdateStoreProductEcommerceRequestImagesItem
    from .update_store_product_ecommerce_request_images_item_variant_ids_item import (
        UpdateStoreProductEcommerceRequestImagesItemVariantIdsItem,
    )
    from .update_store_product_ecommerce_request_variants_item import UpdateStoreProductEcommerceRequestVariantsItem
    from .update_store_product_ecommerce_request_variants_item_price import (
        UpdateStoreProductEcommerceRequestVariantsItemPrice,
    )
    from .update_store_product_image_ecommerce_request_variant_ids_item import (
        UpdateStoreProductImageEcommerceRequestVariantIdsItem,
    )
    from .update_store_product_image_ecommerce_response import UpdateStoreProductImageEcommerceResponse
    from .update_store_product_image_ecommerce_response_links_item import (
        UpdateStoreProductImageEcommerceResponseLinksItem,
    )
    from .update_store_product_image_ecommerce_response_links_item_method import (
        UpdateStoreProductImageEcommerceResponseLinksItemMethod,
    )
    from .update_store_product_variant_ecommerce_request_price import UpdateStoreProductVariantEcommerceRequestPrice
    from .update_store_promo_rule_ecommerce_request_amount import UpdateStorePromoRuleEcommerceRequestAmount
    from .update_store_promo_rule_ecommerce_request_ends_at import UpdateStorePromoRuleEcommerceRequestEndsAt
    from .update_store_promo_rule_ecommerce_request_ends_at_one import UpdateStorePromoRuleEcommerceRequestEndsAtOne
    from .update_store_promo_rule_ecommerce_request_ends_at_zero import UpdateStorePromoRuleEcommerceRequestEndsAtZero
    from .update_store_promo_rule_ecommerce_request_starts_at import UpdateStorePromoRuleEcommerceRequestStartsAt
    from .update_store_promo_rule_ecommerce_request_starts_at_one import UpdateStorePromoRuleEcommerceRequestStartsAtOne
    from .update_store_promo_rule_ecommerce_request_starts_at_zero import (
        UpdateStorePromoRuleEcommerceRequestStartsAtZero,
    )
    from .update_store_promo_rule_ecommerce_request_target import UpdateStorePromoRuleEcommerceRequestTarget
    from .update_store_promo_rule_ecommerce_request_type import UpdateStorePromoRuleEcommerceRequestType
    from .upsert_store_customer_ecommerce_request_address import UpsertStoreCustomerEcommerceRequestAddress
    from .upsert_store_customer_ecommerce_request_total_spent import UpsertStoreCustomerEcommerceRequestTotalSpent
    from .upsert_store_product_ecommerce_request_id import UpsertStoreProductEcommerceRequestId
    from .upsert_store_product_ecommerce_request_images_item import UpsertStoreProductEcommerceRequestImagesItem
    from .upsert_store_product_ecommerce_request_images_item_variant_ids_item import (
        UpsertStoreProductEcommerceRequestImagesItemVariantIdsItem,
    )
    from .upsert_store_product_ecommerce_request_variants_item import UpsertStoreProductEcommerceRequestVariantsItem
    from .upsert_store_product_ecommerce_request_variants_item_id import (
        UpsertStoreProductEcommerceRequestVariantsItemId,
    )
    from .upsert_store_product_ecommerce_request_variants_item_price import (
        UpsertStoreProductEcommerceRequestVariantsItemPrice,
    )
    from .upsert_store_product_variant_ecommerce_request_price import UpsertStoreProductVariantEcommerceRequestPrice
_dynamic_imports: typing.Dict[str, str] = {
    "CreateStoreCartEcommerceRequestId": ".create_store_cart_ecommerce_request_id",
    "CreateStoreCartEcommerceRequestLinesItem": ".create_store_cart_ecommerce_request_lines_item",
    "CreateStoreCartEcommerceRequestLinesItemPrice": ".create_store_cart_ecommerce_request_lines_item_price",
    "CreateStoreCartEcommerceRequestOrderTotal": ".create_store_cart_ecommerce_request_order_total",
    "CreateStoreCartEcommerceRequestTaxTotal": ".create_store_cart_ecommerce_request_tax_total",
    "CreateStoreCartLineEcommerceRequestPrice": ".create_store_cart_line_ecommerce_request_price",
    "CreateStoreCustomerEcommerceRequestAddress": ".create_store_customer_ecommerce_request_address",
    "CreateStoreCustomerEcommerceRequestTotalSpent": ".create_store_customer_ecommerce_request_total_spent",
    "CreateStoreEcommerceRequestAddress": ".create_store_ecommerce_request_address",
    "CreateStoreEcommerceRequestAddressLatitude": ".create_store_ecommerce_request_address_latitude",
    "CreateStoreEcommerceRequestAddressLongitude": ".create_store_ecommerce_request_address_longitude",
    "CreateStoreOrderEcommerceRequestBillingAddress": ".create_store_order_ecommerce_request_billing_address",
    "CreateStoreOrderEcommerceRequestBillingAddressLatitude": ".create_store_order_ecommerce_request_billing_address_latitude",
    "CreateStoreOrderEcommerceRequestBillingAddressLongitude": ".create_store_order_ecommerce_request_billing_address_longitude",
    "CreateStoreOrderEcommerceRequestCartId": ".create_store_order_ecommerce_request_cart_id",
    "CreateStoreOrderEcommerceRequestDiscountTotal": ".create_store_order_ecommerce_request_discount_total",
    "CreateStoreOrderEcommerceRequestLinesItem": ".create_store_order_ecommerce_request_lines_item",
    "CreateStoreOrderEcommerceRequestLinesItemDiscount": ".create_store_order_ecommerce_request_lines_item_discount",
    "CreateStoreOrderEcommerceRequestLinesItemPrice": ".create_store_order_ecommerce_request_lines_item_price",
    "CreateStoreOrderEcommerceRequestOrderTotal": ".create_store_order_ecommerce_request_order_total",
    "CreateStoreOrderEcommerceRequestOutreach": ".create_store_order_ecommerce_request_outreach",
    "CreateStoreOrderEcommerceRequestPromosItem": ".create_store_order_ecommerce_request_promos_item",
    "CreateStoreOrderEcommerceRequestPromosItemAmountDiscounted": ".create_store_order_ecommerce_request_promos_item_amount_discounted",
    "CreateStoreOrderEcommerceRequestPromosItemType": ".create_store_order_ecommerce_request_promos_item_type",
    "CreateStoreOrderEcommerceRequestShippingAddress": ".create_store_order_ecommerce_request_shipping_address",
    "CreateStoreOrderEcommerceRequestShippingAddressLatitude": ".create_store_order_ecommerce_request_shipping_address_latitude",
    "CreateStoreOrderEcommerceRequestShippingAddressLongitude": ".create_store_order_ecommerce_request_shipping_address_longitude",
    "CreateStoreOrderEcommerceRequestShippingTotal": ".create_store_order_ecommerce_request_shipping_total",
    "CreateStoreOrderEcommerceRequestTaxTotal": ".create_store_order_ecommerce_request_tax_total",
    "CreateStoreOrderEcommerceRequestTrackingCode": ".create_store_order_ecommerce_request_tracking_code",
    "CreateStoreOrderLineEcommerceRequestDiscount": ".create_store_order_line_ecommerce_request_discount",
    "CreateStoreOrderLineEcommerceRequestPrice": ".create_store_order_line_ecommerce_request_price",
    "CreateStoreProductImageEcommerceRequestVariantIdsItem": ".create_store_product_image_ecommerce_request_variant_ids_item",
    "CreateStoreProductImageEcommerceResponse": ".create_store_product_image_ecommerce_response",
    "CreateStoreProductImageEcommerceResponseLinksItem": ".create_store_product_image_ecommerce_response_links_item",
    "CreateStoreProductImageEcommerceResponseLinksItemMethod": ".create_store_product_image_ecommerce_response_links_item_method",
    "CreateStoreProductVariantEcommerceRequestId": ".create_store_product_variant_ecommerce_request_id",
    "CreateStoreProductVariantEcommerceRequestPrice": ".create_store_product_variant_ecommerce_request_price",
    "CreateStorePromoRuleEcommerceRequestAmount": ".create_store_promo_rule_ecommerce_request_amount",
    "CreateStorePromoRuleEcommerceRequestEndsAt": ".create_store_promo_rule_ecommerce_request_ends_at",
    "CreateStorePromoRuleEcommerceRequestEndsAtOne": ".create_store_promo_rule_ecommerce_request_ends_at_one",
    "CreateStorePromoRuleEcommerceRequestEndsAtZero": ".create_store_promo_rule_ecommerce_request_ends_at_zero",
    "CreateStorePromoRuleEcommerceRequestStartsAt": ".create_store_promo_rule_ecommerce_request_starts_at",
    "CreateStorePromoRuleEcommerceRequestStartsAtOne": ".create_store_promo_rule_ecommerce_request_starts_at_one",
    "CreateStorePromoRuleEcommerceRequestStartsAtZero": ".create_store_promo_rule_ecommerce_request_starts_at_zero",
    "CreateStorePromoRuleEcommerceRequestTarget": ".create_store_promo_rule_ecommerce_request_target",
    "CreateStorePromoRuleEcommerceRequestType": ".create_store_promo_rule_ecommerce_request_type",
    "GetStoreProductImageEcommerceResponse": ".get_store_product_image_ecommerce_response",
    "GetStoreProductImageEcommerceResponseLinksItem": ".get_store_product_image_ecommerce_response_links_item",
    "GetStoreProductImageEcommerceResponseLinksItemMethod": ".get_store_product_image_ecommerce_response_links_item_method",
    "ListEcommerceResponse": ".list_ecommerce_response",
    "ListEcommerceResponseLinksItem": ".list_ecommerce_response_links_item",
    "ListEcommerceResponseLinksItemMethod": ".list_ecommerce_response_links_item_method",
    "ListOrdersEcommerceResponse": ".list_orders_ecommerce_response",
    "ListOrdersEcommerceResponseLinksItem": ".list_orders_ecommerce_response_links_item",
    "ListOrdersEcommerceResponseLinksItemMethod": ".list_orders_ecommerce_response_links_item_method",
    "ListStoreCartLinesEcommerceResponse": ".list_store_cart_lines_ecommerce_response",
    "ListStoreCartLinesEcommerceResponseLinksItem": ".list_store_cart_lines_ecommerce_response_links_item",
    "ListStoreCartLinesEcommerceResponseLinksItemMethod": ".list_store_cart_lines_ecommerce_response_links_item_method",
    "ListStoreCartsEcommerceResponse": ".list_store_carts_ecommerce_response",
    "ListStoreCartsEcommerceResponseLinksItem": ".list_store_carts_ecommerce_response_links_item",
    "ListStoreCartsEcommerceResponseLinksItemMethod": ".list_store_carts_ecommerce_response_links_item_method",
    "ListStoreCustomersEcommerceResponse": ".list_store_customers_ecommerce_response",
    "ListStoreCustomersEcommerceResponseLinksItem": ".list_store_customers_ecommerce_response_links_item",
    "ListStoreCustomersEcommerceResponseLinksItemMethod": ".list_store_customers_ecommerce_response_links_item_method",
    "ListStoreOrderLinesEcommerceResponse": ".list_store_order_lines_ecommerce_response",
    "ListStoreOrderLinesEcommerceResponseLinksItem": ".list_store_order_lines_ecommerce_response_links_item",
    "ListStoreOrderLinesEcommerceResponseLinksItemMethod": ".list_store_order_lines_ecommerce_response_links_item_method",
    "ListStoreOrdersEcommerceResponse": ".list_store_orders_ecommerce_response",
    "ListStoreOrdersEcommerceResponseLinksItem": ".list_store_orders_ecommerce_response_links_item",
    "ListStoreOrdersEcommerceResponseLinksItemMethod": ".list_store_orders_ecommerce_response_links_item_method",
    "ListStoreProductImagesEcommerceResponse": ".list_store_product_images_ecommerce_response",
    "ListStoreProductImagesEcommerceResponseImagesItem": ".list_store_product_images_ecommerce_response_images_item",
    "ListStoreProductImagesEcommerceResponseImagesItemLinksItem": ".list_store_product_images_ecommerce_response_images_item_links_item",
    "ListStoreProductImagesEcommerceResponseImagesItemLinksItemMethod": ".list_store_product_images_ecommerce_response_images_item_links_item_method",
    "ListStoreProductImagesEcommerceResponseLinksItem": ".list_store_product_images_ecommerce_response_links_item",
    "ListStoreProductImagesEcommerceResponseLinksItemMethod": ".list_store_product_images_ecommerce_response_links_item_method",
    "ListStoreProductVariantsEcommerceResponse": ".list_store_product_variants_ecommerce_response",
    "ListStoreProductVariantsEcommerceResponseLinksItem": ".list_store_product_variants_ecommerce_response_links_item",
    "ListStoreProductVariantsEcommerceResponseLinksItemMethod": ".list_store_product_variants_ecommerce_response_links_item_method",
    "ListStoreProductsEcommerceResponse": ".list_store_products_ecommerce_response",
    "ListStoreProductsEcommerceResponseLinksItem": ".list_store_products_ecommerce_response_links_item",
    "ListStoreProductsEcommerceResponseLinksItemMethod": ".list_store_products_ecommerce_response_links_item_method",
    "ListStorePromoRulePromoCodesEcommerceResponse": ".list_store_promo_rule_promo_codes_ecommerce_response",
    "ListStorePromoRulePromoCodesEcommerceResponseLinksItem": ".list_store_promo_rule_promo_codes_ecommerce_response_links_item",
    "ListStorePromoRulePromoCodesEcommerceResponseLinksItemMethod": ".list_store_promo_rule_promo_codes_ecommerce_response_links_item_method",
    "ListStorePromoRulesEcommerceResponse": ".list_store_promo_rules_ecommerce_response",
    "ListStorePromoRulesEcommerceResponseLinksItem": ".list_store_promo_rules_ecommerce_response_links_item",
    "ListStorePromoRulesEcommerceResponseLinksItemMethod": ".list_store_promo_rules_ecommerce_response_links_item_method",
    "ListStoresEcommerceResponse": ".list_stores_ecommerce_response",
    "ListStoresEcommerceResponseLinksItem": ".list_stores_ecommerce_response_links_item",
    "ListStoresEcommerceResponseLinksItemMethod": ".list_stores_ecommerce_response_links_item_method",
    "UpdateStoreCartEcommerceRequestId": ".update_store_cart_ecommerce_request_id",
    "UpdateStoreCartEcommerceRequestLinesItem": ".update_store_cart_ecommerce_request_lines_item",
    "UpdateStoreCartEcommerceRequestLinesItemPrice": ".update_store_cart_ecommerce_request_lines_item_price",
    "UpdateStoreCartEcommerceRequestOrderTotal": ".update_store_cart_ecommerce_request_order_total",
    "UpdateStoreCartEcommerceRequestTaxTotal": ".update_store_cart_ecommerce_request_tax_total",
    "UpdateStoreCartLineEcommerceRequestPrice": ".update_store_cart_line_ecommerce_request_price",
    "UpdateStoreEcommerceRequestAddress": ".update_store_ecommerce_request_address",
    "UpdateStoreEcommerceRequestAddressLatitude": ".update_store_ecommerce_request_address_latitude",
    "UpdateStoreEcommerceRequestAddressLongitude": ".update_store_ecommerce_request_address_longitude",
    "UpdateStoreOrderEcommerceRequestBillingAddress": ".update_store_order_ecommerce_request_billing_address",
    "UpdateStoreOrderEcommerceRequestBillingAddressLatitude": ".update_store_order_ecommerce_request_billing_address_latitude",
    "UpdateStoreOrderEcommerceRequestBillingAddressLongitude": ".update_store_order_ecommerce_request_billing_address_longitude",
    "UpdateStoreOrderEcommerceRequestCartId": ".update_store_order_ecommerce_request_cart_id",
    "UpdateStoreOrderEcommerceRequestDiscountTotal": ".update_store_order_ecommerce_request_discount_total",
    "UpdateStoreOrderEcommerceRequestLinesItem": ".update_store_order_ecommerce_request_lines_item",
    "UpdateStoreOrderEcommerceRequestLinesItemDiscount": ".update_store_order_ecommerce_request_lines_item_discount",
    "UpdateStoreOrderEcommerceRequestLinesItemPrice": ".update_store_order_ecommerce_request_lines_item_price",
    "UpdateStoreOrderEcommerceRequestOrderTotal": ".update_store_order_ecommerce_request_order_total",
    "UpdateStoreOrderEcommerceRequestOutreach": ".update_store_order_ecommerce_request_outreach",
    "UpdateStoreOrderEcommerceRequestPromosItem": ".update_store_order_ecommerce_request_promos_item",
    "UpdateStoreOrderEcommerceRequestPromosItemAmountDiscounted": ".update_store_order_ecommerce_request_promos_item_amount_discounted",
    "UpdateStoreOrderEcommerceRequestPromosItemType": ".update_store_order_ecommerce_request_promos_item_type",
    "UpdateStoreOrderEcommerceRequestShippingAddress": ".update_store_order_ecommerce_request_shipping_address",
    "UpdateStoreOrderEcommerceRequestShippingAddressLatitude": ".update_store_order_ecommerce_request_shipping_address_latitude",
    "UpdateStoreOrderEcommerceRequestShippingAddressLongitude": ".update_store_order_ecommerce_request_shipping_address_longitude",
    "UpdateStoreOrderEcommerceRequestShippingTotal": ".update_store_order_ecommerce_request_shipping_total",
    "UpdateStoreOrderEcommerceRequestTaxTotal": ".update_store_order_ecommerce_request_tax_total",
    "UpdateStoreOrderEcommerceRequestTrackingCode": ".update_store_order_ecommerce_request_tracking_code",
    "UpdateStoreOrderLineEcommerceRequestDiscount": ".update_store_order_line_ecommerce_request_discount",
    "UpdateStoreOrderLineEcommerceRequestPrice": ".update_store_order_line_ecommerce_request_price",
    "UpdateStoreProductEcommerceRequestId": ".update_store_product_ecommerce_request_id",
    "UpdateStoreProductEcommerceRequestImagesItem": ".update_store_product_ecommerce_request_images_item",
    "UpdateStoreProductEcommerceRequestImagesItemVariantIdsItem": ".update_store_product_ecommerce_request_images_item_variant_ids_item",
    "UpdateStoreProductEcommerceRequestVariantsItem": ".update_store_product_ecommerce_request_variants_item",
    "UpdateStoreProductEcommerceRequestVariantsItemPrice": ".update_store_product_ecommerce_request_variants_item_price",
    "UpdateStoreProductImageEcommerceRequestVariantIdsItem": ".update_store_product_image_ecommerce_request_variant_ids_item",
    "UpdateStoreProductImageEcommerceResponse": ".update_store_product_image_ecommerce_response",
    "UpdateStoreProductImageEcommerceResponseLinksItem": ".update_store_product_image_ecommerce_response_links_item",
    "UpdateStoreProductImageEcommerceResponseLinksItemMethod": ".update_store_product_image_ecommerce_response_links_item_method",
    "UpdateStoreProductVariantEcommerceRequestPrice": ".update_store_product_variant_ecommerce_request_price",
    "UpdateStorePromoRuleEcommerceRequestAmount": ".update_store_promo_rule_ecommerce_request_amount",
    "UpdateStorePromoRuleEcommerceRequestEndsAt": ".update_store_promo_rule_ecommerce_request_ends_at",
    "UpdateStorePromoRuleEcommerceRequestEndsAtOne": ".update_store_promo_rule_ecommerce_request_ends_at_one",
    "UpdateStorePromoRuleEcommerceRequestEndsAtZero": ".update_store_promo_rule_ecommerce_request_ends_at_zero",
    "UpdateStorePromoRuleEcommerceRequestStartsAt": ".update_store_promo_rule_ecommerce_request_starts_at",
    "UpdateStorePromoRuleEcommerceRequestStartsAtOne": ".update_store_promo_rule_ecommerce_request_starts_at_one",
    "UpdateStorePromoRuleEcommerceRequestStartsAtZero": ".update_store_promo_rule_ecommerce_request_starts_at_zero",
    "UpdateStorePromoRuleEcommerceRequestTarget": ".update_store_promo_rule_ecommerce_request_target",
    "UpdateStorePromoRuleEcommerceRequestType": ".update_store_promo_rule_ecommerce_request_type",
    "UpsertStoreCustomerEcommerceRequestAddress": ".upsert_store_customer_ecommerce_request_address",
    "UpsertStoreCustomerEcommerceRequestTotalSpent": ".upsert_store_customer_ecommerce_request_total_spent",
    "UpsertStoreProductEcommerceRequestId": ".upsert_store_product_ecommerce_request_id",
    "UpsertStoreProductEcommerceRequestImagesItem": ".upsert_store_product_ecommerce_request_images_item",
    "UpsertStoreProductEcommerceRequestImagesItemVariantIdsItem": ".upsert_store_product_ecommerce_request_images_item_variant_ids_item",
    "UpsertStoreProductEcommerceRequestVariantsItem": ".upsert_store_product_ecommerce_request_variants_item",
    "UpsertStoreProductEcommerceRequestVariantsItemId": ".upsert_store_product_ecommerce_request_variants_item_id",
    "UpsertStoreProductEcommerceRequestVariantsItemPrice": ".upsert_store_product_ecommerce_request_variants_item_price",
    "UpsertStoreProductVariantEcommerceRequestPrice": ".upsert_store_product_variant_ecommerce_request_price",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateStoreCartEcommerceRequestId",
    "CreateStoreCartEcommerceRequestLinesItem",
    "CreateStoreCartEcommerceRequestLinesItemPrice",
    "CreateStoreCartEcommerceRequestOrderTotal",
    "CreateStoreCartEcommerceRequestTaxTotal",
    "CreateStoreCartLineEcommerceRequestPrice",
    "CreateStoreCustomerEcommerceRequestAddress",
    "CreateStoreCustomerEcommerceRequestTotalSpent",
    "CreateStoreEcommerceRequestAddress",
    "CreateStoreEcommerceRequestAddressLatitude",
    "CreateStoreEcommerceRequestAddressLongitude",
    "CreateStoreOrderEcommerceRequestBillingAddress",
    "CreateStoreOrderEcommerceRequestBillingAddressLatitude",
    "CreateStoreOrderEcommerceRequestBillingAddressLongitude",
    "CreateStoreOrderEcommerceRequestCartId",
    "CreateStoreOrderEcommerceRequestDiscountTotal",
    "CreateStoreOrderEcommerceRequestLinesItem",
    "CreateStoreOrderEcommerceRequestLinesItemDiscount",
    "CreateStoreOrderEcommerceRequestLinesItemPrice",
    "CreateStoreOrderEcommerceRequestOrderTotal",
    "CreateStoreOrderEcommerceRequestOutreach",
    "CreateStoreOrderEcommerceRequestPromosItem",
    "CreateStoreOrderEcommerceRequestPromosItemAmountDiscounted",
    "CreateStoreOrderEcommerceRequestPromosItemType",
    "CreateStoreOrderEcommerceRequestShippingAddress",
    "CreateStoreOrderEcommerceRequestShippingAddressLatitude",
    "CreateStoreOrderEcommerceRequestShippingAddressLongitude",
    "CreateStoreOrderEcommerceRequestShippingTotal",
    "CreateStoreOrderEcommerceRequestTaxTotal",
    "CreateStoreOrderEcommerceRequestTrackingCode",
    "CreateStoreOrderLineEcommerceRequestDiscount",
    "CreateStoreOrderLineEcommerceRequestPrice",
    "CreateStoreProductImageEcommerceRequestVariantIdsItem",
    "CreateStoreProductImageEcommerceResponse",
    "CreateStoreProductImageEcommerceResponseLinksItem",
    "CreateStoreProductImageEcommerceResponseLinksItemMethod",
    "CreateStoreProductVariantEcommerceRequestId",
    "CreateStoreProductVariantEcommerceRequestPrice",
    "CreateStorePromoRuleEcommerceRequestAmount",
    "CreateStorePromoRuleEcommerceRequestEndsAt",
    "CreateStorePromoRuleEcommerceRequestEndsAtOne",
    "CreateStorePromoRuleEcommerceRequestEndsAtZero",
    "CreateStorePromoRuleEcommerceRequestStartsAt",
    "CreateStorePromoRuleEcommerceRequestStartsAtOne",
    "CreateStorePromoRuleEcommerceRequestStartsAtZero",
    "CreateStorePromoRuleEcommerceRequestTarget",
    "CreateStorePromoRuleEcommerceRequestType",
    "GetStoreProductImageEcommerceResponse",
    "GetStoreProductImageEcommerceResponseLinksItem",
    "GetStoreProductImageEcommerceResponseLinksItemMethod",
    "ListEcommerceResponse",
    "ListEcommerceResponseLinksItem",
    "ListEcommerceResponseLinksItemMethod",
    "ListOrdersEcommerceResponse",
    "ListOrdersEcommerceResponseLinksItem",
    "ListOrdersEcommerceResponseLinksItemMethod",
    "ListStoreCartLinesEcommerceResponse",
    "ListStoreCartLinesEcommerceResponseLinksItem",
    "ListStoreCartLinesEcommerceResponseLinksItemMethod",
    "ListStoreCartsEcommerceResponse",
    "ListStoreCartsEcommerceResponseLinksItem",
    "ListStoreCartsEcommerceResponseLinksItemMethod",
    "ListStoreCustomersEcommerceResponse",
    "ListStoreCustomersEcommerceResponseLinksItem",
    "ListStoreCustomersEcommerceResponseLinksItemMethod",
    "ListStoreOrderLinesEcommerceResponse",
    "ListStoreOrderLinesEcommerceResponseLinksItem",
    "ListStoreOrderLinesEcommerceResponseLinksItemMethod",
    "ListStoreOrdersEcommerceResponse",
    "ListStoreOrdersEcommerceResponseLinksItem",
    "ListStoreOrdersEcommerceResponseLinksItemMethod",
    "ListStoreProductImagesEcommerceResponse",
    "ListStoreProductImagesEcommerceResponseImagesItem",
    "ListStoreProductImagesEcommerceResponseImagesItemLinksItem",
    "ListStoreProductImagesEcommerceResponseImagesItemLinksItemMethod",
    "ListStoreProductImagesEcommerceResponseLinksItem",
    "ListStoreProductImagesEcommerceResponseLinksItemMethod",
    "ListStoreProductVariantsEcommerceResponse",
    "ListStoreProductVariantsEcommerceResponseLinksItem",
    "ListStoreProductVariantsEcommerceResponseLinksItemMethod",
    "ListStoreProductsEcommerceResponse",
    "ListStoreProductsEcommerceResponseLinksItem",
    "ListStoreProductsEcommerceResponseLinksItemMethod",
    "ListStorePromoRulePromoCodesEcommerceResponse",
    "ListStorePromoRulePromoCodesEcommerceResponseLinksItem",
    "ListStorePromoRulePromoCodesEcommerceResponseLinksItemMethod",
    "ListStorePromoRulesEcommerceResponse",
    "ListStorePromoRulesEcommerceResponseLinksItem",
    "ListStorePromoRulesEcommerceResponseLinksItemMethod",
    "ListStoresEcommerceResponse",
    "ListStoresEcommerceResponseLinksItem",
    "ListStoresEcommerceResponseLinksItemMethod",
    "UpdateStoreCartEcommerceRequestId",
    "UpdateStoreCartEcommerceRequestLinesItem",
    "UpdateStoreCartEcommerceRequestLinesItemPrice",
    "UpdateStoreCartEcommerceRequestOrderTotal",
    "UpdateStoreCartEcommerceRequestTaxTotal",
    "UpdateStoreCartLineEcommerceRequestPrice",
    "UpdateStoreEcommerceRequestAddress",
    "UpdateStoreEcommerceRequestAddressLatitude",
    "UpdateStoreEcommerceRequestAddressLongitude",
    "UpdateStoreOrderEcommerceRequestBillingAddress",
    "UpdateStoreOrderEcommerceRequestBillingAddressLatitude",
    "UpdateStoreOrderEcommerceRequestBillingAddressLongitude",
    "UpdateStoreOrderEcommerceRequestCartId",
    "UpdateStoreOrderEcommerceRequestDiscountTotal",
    "UpdateStoreOrderEcommerceRequestLinesItem",
    "UpdateStoreOrderEcommerceRequestLinesItemDiscount",
    "UpdateStoreOrderEcommerceRequestLinesItemPrice",
    "UpdateStoreOrderEcommerceRequestOrderTotal",
    "UpdateStoreOrderEcommerceRequestOutreach",
    "UpdateStoreOrderEcommerceRequestPromosItem",
    "UpdateStoreOrderEcommerceRequestPromosItemAmountDiscounted",
    "UpdateStoreOrderEcommerceRequestPromosItemType",
    "UpdateStoreOrderEcommerceRequestShippingAddress",
    "UpdateStoreOrderEcommerceRequestShippingAddressLatitude",
    "UpdateStoreOrderEcommerceRequestShippingAddressLongitude",
    "UpdateStoreOrderEcommerceRequestShippingTotal",
    "UpdateStoreOrderEcommerceRequestTaxTotal",
    "UpdateStoreOrderEcommerceRequestTrackingCode",
    "UpdateStoreOrderLineEcommerceRequestDiscount",
    "UpdateStoreOrderLineEcommerceRequestPrice",
    "UpdateStoreProductEcommerceRequestId",
    "UpdateStoreProductEcommerceRequestImagesItem",
    "UpdateStoreProductEcommerceRequestImagesItemVariantIdsItem",
    "UpdateStoreProductEcommerceRequestVariantsItem",
    "UpdateStoreProductEcommerceRequestVariantsItemPrice",
    "UpdateStoreProductImageEcommerceRequestVariantIdsItem",
    "UpdateStoreProductImageEcommerceResponse",
    "UpdateStoreProductImageEcommerceResponseLinksItem",
    "UpdateStoreProductImageEcommerceResponseLinksItemMethod",
    "UpdateStoreProductVariantEcommerceRequestPrice",
    "UpdateStorePromoRuleEcommerceRequestAmount",
    "UpdateStorePromoRuleEcommerceRequestEndsAt",
    "UpdateStorePromoRuleEcommerceRequestEndsAtOne",
    "UpdateStorePromoRuleEcommerceRequestEndsAtZero",
    "UpdateStorePromoRuleEcommerceRequestStartsAt",
    "UpdateStorePromoRuleEcommerceRequestStartsAtOne",
    "UpdateStorePromoRuleEcommerceRequestStartsAtZero",
    "UpdateStorePromoRuleEcommerceRequestTarget",
    "UpdateStorePromoRuleEcommerceRequestType",
    "UpsertStoreCustomerEcommerceRequestAddress",
    "UpsertStoreCustomerEcommerceRequestTotalSpent",
    "UpsertStoreProductEcommerceRequestId",
    "UpsertStoreProductEcommerceRequestImagesItem",
    "UpsertStoreProductEcommerceRequestImagesItemVariantIdsItem",
    "UpsertStoreProductEcommerceRequestVariantsItem",
    "UpsertStoreProductEcommerceRequestVariantsItemId",
    "UpsertStoreProductEcommerceRequestVariantsItemPrice",
    "UpsertStoreProductVariantEcommerceRequestPrice",
]
