# This file was auto-generated from our API Definition.

import typing

from .create_store_promo_rule_ecommerce_request_starts_at_one import CreateStorePromoRuleEcommerceRequestStartsAtOne
from .create_store_promo_rule_ecommerce_request_starts_at_zero import CreateStorePromoRuleEcommerceRequestStartsAtZero

CreateStorePromoRuleEcommerceRequestStartsAt = typing.Union[
    CreateStorePromoRuleEcommerceRequestStartsAtZero, CreateStorePromoRuleEcommerceRequestStartsAtOne
]
