# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_store_order_ecommerce_request_shipping_address_latitude import (
    CreateStoreOrderEcommerceRequestShippingAddressLatitude,
)
from .create_store_order_ecommerce_request_shipping_address_longitude import (
    CreateStoreOrderEcommerceRequestShippingAddressLongitude,
)


class CreateStoreOrderEcommerceRequestShippingAddress(UniversalBaseModel):
    """
    The shipping address for the order.
    """

    address1: typing.Optional[str] = pydantic.Field(default=None)
    """
    The shipping address for the order.
    """

    address2: typing.Optional[str] = pydantic.Field(default=None)
    """
    An additional field for the shipping address.
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    The city in the order's shipping address.
    """

    company: typing.Optional[str] = pydantic.Field(default=None)
    """
    The company associated with the shipping address.
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    The country in the shipping address.
    """

    country_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The two-letter code for the country in the shipping address.
    """

    latitude: typing.Optional[CreateStoreOrderEcommerceRequestShippingAddressLatitude] = pydantic.Field(default=None)
    """
    The latitude for the shipping address location.
    """

    longitude: typing.Optional[CreateStoreOrderEcommerceRequestShippingAddressLongitude] = pydantic.Field(default=None)
    """
    The longitude for the shipping address location.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name associated with an order's shipping address.
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    The phone number for the order's shipping address.
    """

    postal_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The postal or zip code in the shipping address.
    """

    province: typing.Optional[str] = pydantic.Field(default=None)
    """
    The state or normalized province in the order's shipping address.
    """

    province_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The two-letter code for the province or state in the shipping address.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
