# This file was auto-generated from our API Definition.

import typing

from .update_store_promo_rule_ecommerce_request_starts_at_one import UpdateStorePromoRuleEcommerceRequestStartsAtOne
from .update_store_promo_rule_ecommerce_request_starts_at_zero import UpdateStorePromoRuleEcommerceRequestStartsAtZero

UpdateStorePromoRuleEcommerceRequestStartsAt = typing.Union[
    UpdateStorePromoRuleEcommerceRequestStartsAtZero, UpdateStorePromoRuleEcommerceRequestStartsAtOne
]
