# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_store_cart_ecommerce_request_lines_item_price import UpdateStoreCartEcommerceRequestLinesItemPrice


class UpdateStoreCartEcommerceRequestLinesItem(UniversalBaseModel):
    """
    Information about a specific cart line item.
    """

    price: typing.Optional[UpdateStoreCartEcommerceRequestLinesItemPrice] = None
    product_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique identifier for the product associated with the cart line item.
    """

    product_variant_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique identifier for the product variant associated with the cart line item.
    """

    quantity: typing.Optional[int] = pydantic.Field(default=None)
    """
    The quantity of a cart line item.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
