# This file was auto-generated from our API Definition.

import typing

from .update_store_promo_rule_ecommerce_request_ends_at_one import UpdateStorePromoRuleEcommerceRequestEndsAtOne
from .update_store_promo_rule_ecommerce_request_ends_at_zero import UpdateStorePromoRuleEcommerceRequestEndsAtZero

UpdateStorePromoRuleEcommerceRequestEndsAt = typing.Union[
    UpdateStorePromoRuleEcommerceRequestEndsAtZero, UpdateStorePromoRuleEcommerceRequestEndsAtOne
]
