# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawVerifiedDomainsClient, RawVerifiedDomainsClient
from .types.create_action_verify_verified_domains_response import CreateActionVerifyVerifiedDomainsResponse
from .types.create_verified_domains_response import CreateVerifiedDomainsResponse
from .types.get_verified_domains_response import GetVerifiedDomainsResponse
from .types.list_verified_domains_response import ListVerifiedDomainsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VerifiedDomainsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVerifiedDomainsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVerifiedDomainsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVerifiedDomainsClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListVerifiedDomainsResponse:
        """
        Get all of the sending domains on the account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListVerifiedDomainsResponse
            The domains on the account.

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.verified_domains.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self, *, verification_email: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateVerifiedDomainsResponse:
        """
        Add a domain to the account.

        Parameters
        ----------
        verification_email : str
            The e-mail address at the domain you want to verify. This will receive a two-factor challenge to be used in the verify action.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateVerifiedDomainsResponse
            The newly-created domain.

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.verified_domains.create(
            verification_email="verification_email",
        )
        """
        _response = self._raw_client.create(verification_email=verification_email, request_options=request_options)
        return _response.data

    def get(
        self, domain_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetVerifiedDomainsResponse:
        """
        Get the details for a single domain on the account.

        Parameters
        ----------
        domain_name : str
            The domain name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetVerifiedDomainsResponse


        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.verified_domains.get(
            domain_name="domain_name",
        )
        """
        _response = self._raw_client.get(domain_name, request_options=request_options)
        return _response.data

    def delete(self, domain_name: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a verified domain from the account.

        Parameters
        ----------
        domain_name : str
            The domain name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.verified_domains.delete(
            domain_name="domain_name",
        )
        """
        _response = self._raw_client.delete(domain_name, request_options=request_options)
        return _response.data

    def create_action_verify(
        self, domain_name: str, *, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateActionVerifyVerifiedDomainsResponse:
        """
        Verify a domain for sending.

        Parameters
        ----------
        domain_name : str
            The domain name.

        code : str
            The code that was sent to the email address provided when adding a new domain to verify.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateActionVerifyVerifiedDomainsResponse
            The domain being verified for sending.

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.verified_domains.create_action_verify(
            domain_name="domain_name",
            code="code",
        )
        """
        _response = self._raw_client.create_action_verify(domain_name, code=code, request_options=request_options)
        return _response.data


class AsyncVerifiedDomainsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVerifiedDomainsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVerifiedDomainsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVerifiedDomainsClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListVerifiedDomainsResponse:
        """
        Get all of the sending domains on the account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListVerifiedDomainsResponse
            The domains on the account.

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.verified_domains.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self, *, verification_email: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateVerifiedDomainsResponse:
        """
        Add a domain to the account.

        Parameters
        ----------
        verification_email : str
            The e-mail address at the domain you want to verify. This will receive a two-factor challenge to be used in the verify action.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateVerifiedDomainsResponse
            The newly-created domain.

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.verified_domains.create(
                verification_email="verification_email",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            verification_email=verification_email, request_options=request_options
        )
        return _response.data

    async def get(
        self, domain_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetVerifiedDomainsResponse:
        """
        Get the details for a single domain on the account.

        Parameters
        ----------
        domain_name : str
            The domain name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetVerifiedDomainsResponse


        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.verified_domains.get(
                domain_name="domain_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(domain_name, request_options=request_options)
        return _response.data

    async def delete(self, domain_name: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a verified domain from the account.

        Parameters
        ----------
        domain_name : str
            The domain name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.verified_domains.delete(
                domain_name="domain_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(domain_name, request_options=request_options)
        return _response.data

    async def create_action_verify(
        self, domain_name: str, *, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateActionVerifyVerifiedDomainsResponse:
        """
        Verify a domain for sending.

        Parameters
        ----------
        domain_name : str
            The domain name.

        code : str
            The code that was sent to the email address provided when adding a new domain to verify.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateActionVerifyVerifiedDomainsResponse
            The domain being verified for sending.

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.verified_domains.create_action_verify(
                domain_name="domain_name",
                code="code",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_action_verify(domain_name, code=code, request_options=request_options)
        return _response.data
