# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawCustomerJourneysClient, RawCustomerJourneysClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CustomerJourneysClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCustomerJourneysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCustomerJourneysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCustomerJourneysClient
        """
        return self._raw_client

    def create_journey_step_action_trigger(
        self,
        journey_id: int,
        step_id: int,
        *,
        email_address: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        A step trigger in an Automation flow. To use it, create a starting point or step from the Automation flow builder in the app using the Customer Journeys API condition. We’ll provide a url during the process that includes the {journey_id} and {step_id}. You’ll then be able to use this endpoint to trigger the condition for the posted contact.

        Parameters
        ----------
        journey_id : int
            The id for the flow.

        step_id : int
            The id for the Step.

        email_address : str
            The list member's email address.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.customer_journeys.create_journey_step_action_trigger(
            journey_id=1,
            step_id=1,
            email_address="email_address",
        )
        """
        _response = self._raw_client.create_journey_step_action_trigger(
            journey_id, step_id, email_address=email_address, request_options=request_options
        )
        return _response.data


class AsyncCustomerJourneysClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCustomerJourneysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCustomerJourneysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCustomerJourneysClient
        """
        return self._raw_client

    async def create_journey_step_action_trigger(
        self,
        journey_id: int,
        step_id: int,
        *,
        email_address: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        A step trigger in an Automation flow. To use it, create a starting point or step from the Automation flow builder in the app using the Customer Journeys API condition. We’ll provide a url during the process that includes the {journey_id} and {step_id}. You’ll then be able to use this endpoint to trigger the condition for the posted contact.

        Parameters
        ----------
        journey_id : int
            The id for the flow.

        step_id : int
            The id for the Step.

        email_address : str
            The list member's email address.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customer_journeys.create_journey_step_action_trigger(
                journey_id=1,
                step_id=1,
                email_address="email_address",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_journey_step_action_trigger(
            journey_id, step_id, email_address=email_address, request_options=request_options
        )
        return _response.data
