# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .list_conversations_request_has_unread_messages import ListConversationsRequestHasUnreadMessages
    from .list_conversations_response import ListConversationsResponse
    from .list_conversations_response_links_item import ListConversationsResponseLinksItem
    from .list_conversations_response_links_item_method import ListConversationsResponseLinksItemMethod
    from .list_messages_conversations_request_is_read import ListMessagesConversationsRequestIsRead
    from .list_messages_conversations_response import ListMessagesConversationsResponse
    from .list_messages_conversations_response_links_item import ListMessagesConversationsResponseLinksItem
    from .list_messages_conversations_response_links_item_method import ListMessagesConversationsResponseLinksItemMethod
_dynamic_imports: typing.Dict[str, str] = {
    "ListConversationsRequestHasUnreadMessages": ".list_conversations_request_has_unread_messages",
    "ListConversationsResponse": ".list_conversations_response",
    "ListConversationsResponseLinksItem": ".list_conversations_response_links_item",
    "ListConversationsResponseLinksItemMethod": ".list_conversations_response_links_item_method",
    "ListMessagesConversationsRequestIsRead": ".list_messages_conversations_request_is_read",
    "ListMessagesConversationsResponse": ".list_messages_conversations_response",
    "ListMessagesConversationsResponseLinksItem": ".list_messages_conversations_response_links_item",
    "ListMessagesConversationsResponseLinksItemMethod": ".list_messages_conversations_response_links_item_method",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ListConversationsRequestHasUnreadMessages",
    "ListConversationsResponse",
    "ListConversationsResponseLinksItem",
    "ListConversationsResponseLinksItemMethod",
    "ListMessagesConversationsRequestIsRead",
    "ListMessagesConversationsResponse",
    "ListMessagesConversationsResponseLinksItem",
    "ListMessagesConversationsResponseLinksItemMethod",
]
