# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawActivityFeedClient, RawActivityFeedClient
from .types.list_activity_feed_response_item import ListActivityFeedResponseItem
from .types.list_chimp_chatter_activity_feed_response import ListChimpChatterActivityFeedResponse
from .types.list_chimp_chatter_activity_feed_response_chimp_chatter_item import (
    ListChimpChatterActivityFeedResponseChimpChatterItem,
)


class ActivityFeedClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawActivityFeedClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawActivityFeedClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawActivityFeedClient
        """
        return self._raw_client

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListActivityFeedResponseItem]:
        """
        Get information about the activity feed endpoint's resources.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListActivityFeedResponseItem]


        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        client.activity_feed.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def list_chimp_chatter(
        self,
        *,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ListChimpChatterActivityFeedResponseChimpChatterItem, ListChimpChatterActivityFeedResponse]:
        """
        Return the Chimp Chatter for this account ordered by most recent.

        Parameters
        ----------
        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ListChimpChatterActivityFeedResponseChimpChatterItem, ListChimpChatterActivityFeedResponse]
            ChimpChatter Collection

        Examples
        --------
        from mailchimp_marketing import MailchimpClient

        client = MailchimpClient(
            token="YOUR_TOKEN",
        )
        response = client.activity_feed.list_chimp_chatter()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_chimp_chatter(count=count, offset=offset, request_options=request_options)


class AsyncActivityFeedClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawActivityFeedClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawActivityFeedClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawActivityFeedClient
        """
        return self._raw_client

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListActivityFeedResponseItem]:
        """
        Get information about the activity feed endpoint's resources.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListActivityFeedResponseItem]


        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.activity_feed.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def list_chimp_chatter(
        self,
        *,
        count: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ListChimpChatterActivityFeedResponseChimpChatterItem, ListChimpChatterActivityFeedResponse]:
        """
        Return the Chimp Chatter for this account ordered by most recent.

        Parameters
        ----------
        count : typing.Optional[int]
            The number of records to return. Default value is 10. Maximum value is 1000

        offset : typing.Optional[int]
            Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ListChimpChatterActivityFeedResponseChimpChatterItem, ListChimpChatterActivityFeedResponse]
            ChimpChatter Collection

        Examples
        --------
        import asyncio

        from mailchimp_marketing import AsyncMailchimpClient

        client = AsyncMailchimpClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.activity_feed.list_chimp_chatter()
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_chimp_chatter(count=count, offset=offset, request_options=request_options)
