# This file was auto-generated by Fern from our API Definition.

import typing

from .batch_subscribe_or_unsubscribe_lists_request_members_item_timestamp_signup_one import (
    BatchSubscribeOrUnsubscribeListsRequestMembersItemTimestampSignupOne,
)

BatchSubscribeOrUnsubscribeListsRequestMembersItemTimestampSignup = typing.Union[
    str, BatchSubscribeOrUnsubscribeListsRequestMembersItemTimestampSignupOne
]
