# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_member_lists_request_location_latitude import CreateMemberListsRequestLocationLatitude
from .create_member_lists_request_location_longitude import CreateMemberListsRequestLocationLongitude


class CreateMemberListsRequestLocation(UniversalBaseModel):
    """
    Subscriber location information.
    """

    latitude: typing.Optional[CreateMemberListsRequestLocationLatitude] = None
    longitude: typing.Optional[CreateMemberListsRequestLocationLongitude] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
