# This file was auto-generated by Fern from our API Definition.

import typing

CreateMergeFieldListsRequestType = typing.Union[
    typing.Literal[
        "text", "number", "address", "phone", "date", "url", "imageurl", "radio", "dropdown", "birthday", "zip"
    ],
    typing.Any,
]
