# This file was auto-generated by Fern from our API Definition.

import typing

CreateSignupFormListsRequestHeaderImageAlign = typing.Union[
    typing.Literal["none", "left", "center", "right"], typing.Any
]
