# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.merge_field import MergeField
from .list_merge_fields_lists_response_links_item import ListMergeFieldsListsResponseLinksItem


class ListMergeFieldsListsResponse(UniversalBaseModel):
    """
    The [merge fields](https://mailchimp.com/developer/marketing/docs/merge-fields/) for an audience.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[ListMergeFieldsListsResponseLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    list_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The list id.
    """

    merge_field_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    The maximum number of merge fields this audience can hold. The limit is determined by the account's plan. Subtract `total_items` from this value to derive the remaining capacity.
    """

    merge_fields: typing.Optional[typing.List[MergeField]] = pydantic.Field(default=None)
    """
    An array of objects, each representing a merge field resource.
    """

    total_items: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of items matching the query regardless of pagination.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
