# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .list_member_activity_lists_response_activity_item import ListMemberActivityListsResponseActivityItem
from .list_member_activity_lists_response_links_item import ListMemberActivityListsResponseLinksItem


class ListMemberActivityListsResponse(UniversalBaseModel):
    """
    The last 50 member events for a list.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[ListMemberActivityListsResponseLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    activity: typing.Optional[typing.List[ListMemberActivityListsResponseActivityItem]] = pydantic.Field(default=None)
    """
    An array of objects, each representing a member event.
    """

    contact_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    As Mailchimp evolves beyond email, you may eventually have contacts without email addresses. While the `email_id` is the MD5 hash of their email address, this `contact_id` is agnostic of contact’s inclusion of an email address.
    """

    email_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The MD5 hash of the lowercase version of the list member's email address.
    """

    list_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The list id.
    """

    total_items: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of items matching the query regardless of pagination.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
