# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .list_member_tags_lists_response_links_item import ListMemberTagsListsResponseLinksItem
from .list_member_tags_lists_response_tags_item import ListMemberTagsListsResponseTagsItem


class ListMemberTagsListsResponse(UniversalBaseModel):
    """
    A list of tags assigned to a list member.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[ListMemberTagsListsResponseLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    tags: typing.Optional[typing.List[ListMemberTagsListsResponseTagsItem]] = pydantic.Field(default=None)
    """
    A list of tags assigned to the list member.
    """

    total_items: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of items matching the query regardless of pagination.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
