# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListMemberGoalsListsResponseGoalsItem(UniversalBaseModel):
    """
    A single instance of a goal activity.
    """

    data: typing.Optional[str] = pydantic.Field(default=None)
    """
    Any extra data passed with the Goal event.
    """

    event: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name/type of Goal event triggered.
    """

    goal_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    The id for a Goal event.
    """

    last_visited_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the user last triggered the Goal event in ISO 8601 format.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
