# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateMergeFieldListsRequestOptions(UniversalBaseModel):
    """
    Extra options for some merge field types.
    """

    choices: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    In a radio or dropdown non-group field, the available options for members to pick from.
    """

    date_format: typing.Optional[str] = pydantic.Field(default=None)
    """
    In a date or birthday field, the format of the date.
    """

    default_country: typing.Optional[int] = pydantic.Field(default=None)
    """
    In an address field, the default country code if none supplied.
    """

    phone_format: typing.Optional[str] = pydantic.Field(default=None)
    """
    In a phone field, the phone number type: US or International.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
