# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ab_testing_options_pick_winner import AbTestingOptionsPickWinner
from .ab_testing_options_split_test import AbTestingOptionsSplitTest
from .ab_testing_options_wait_units import AbTestingOptionsWaitUnits


class AbTestingOptions(UniversalBaseModel):
    """
    [A/B Testing](https://mailchimp.com/help/about-ab-tests/) options for a campaign.
    """

    from_name_a: typing.Optional[str] = pydantic.Field(default=None)
    """
    For campaigns split on 'From Name', the name for Group A.
    """

    from_name_b: typing.Optional[str] = pydantic.Field(default=None)
    """
    For campaigns split on 'From Name', the name for Group B.
    """

    pick_winner: typing.Optional[AbTestingOptionsPickWinner] = pydantic.Field(default=None)
    """
    How we should evaluate a winner. Based on 'opens', 'clicks', or 'manual'.
    """

    reply_email_a: typing.Optional[str] = pydantic.Field(default=None)
    """
    For campaigns split on 'From Name', the reply-to address for Group A.
    """

    reply_email_b: typing.Optional[str] = pydantic.Field(default=None)
    """
    For campaigns split on 'From Name', the reply-to address for Group B.
    """

    send_time_a: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The send time for Group A.
    """

    send_time_b: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The send time for Group B.
    """

    send_time_winner: typing.Optional[str] = pydantic.Field(default=None)
    """
    The send time for the winning version.
    """

    split_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    The size of the split groups. Campaigns split based on 'schedule' are forced to have a 50/50 split. Valid split integers are between 1-50.
    """

    split_test: typing.Optional[AbTestingOptionsSplitTest] = pydantic.Field(default=None)
    """
    The type of AB split to run.
    """

    subject_a: typing.Optional[str] = pydantic.Field(default=None)
    """
    For campaigns split on 'Subject Line', the subject line for Group A.
    """

    subject_b: typing.Optional[str] = pydantic.Field(default=None)
    """
    For campaigns split on 'Subject Line', the subject line for Group B.
    """

    wait_time: typing.Optional[int] = pydantic.Field(default=None)
    """
    The amount of time to wait before picking a winner. This cannot be changed after a campaign is sent.
    """

    wait_units: typing.Optional[AbTestingOptionsWaitUnits] = pydantic.Field(default=None)
    """
    How unit of time for measuring the winner ('hours' or 'days'). This cannot be changed after a campaign is sent.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
