# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .add_webhook_events import AddWebhookEvents
from .add_webhook_sources import AddWebhookSources


class AddWebhook(UniversalBaseModel):
    """
    Configure a webhook for the given list.
    """

    events: typing.Optional[AddWebhookEvents] = pydantic.Field(default=None)
    """
    The events that can trigger the webhook and whether they are enabled.
    """

    sources: typing.Optional[AddWebhookSources] = pydantic.Field(default=None)
    """
    The possible sources of any events that can trigger the webhook and whether they are enabled.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    A valid URL for the Webhook.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
