# This file was auto-generated by Fern from our API Definition.

import typing

AutomationWorkflowEmailTriggerSettingsRuntimeDaysItem = typing.Union[
    typing.Literal["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"], typing.Any
]
