# This file was auto-generated by Fern from our API Definition.

import typing

AutomationWorkflowEmailTriggerSettingsRuntimeHoursType = typing.Union[
    typing.Literal["send_asap", "send_between", "send_at"], typing.Any
]
