# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AutomationWorkflowTrackingSalesforce(UniversalBaseModel):
    """
    Deprecated
    """

    campaign: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Create a campaign in a connected Salesforce account.
    """

    notes: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Update contact notes for a campaign based on a subscriber's email address.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
