# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .automation_workflow_email_delay_action import AutomationWorkflowEmailDelayAction
from .automation_workflow_email_delay_direction import AutomationWorkflowEmailDelayDirection
from .automation_workflow_email_delay_type import AutomationWorkflowEmailDelayType


class AutomationWorkflowEmailDelay(UniversalBaseModel):
    """
    The delay settings for an Automation email.
    """

    action: typing.Optional[AutomationWorkflowEmailDelayAction] = pydantic.Field(default=None)
    """
    The action that triggers the delay of an Automation email.
    """

    action_description: typing.Optional[str] = pydantic.Field(default=None)
    """
    The user-friendly description of the action that triggers an Automation email.
    """

    amount: typing.Optional[int] = pydantic.Field(default=None)
    """
    The delay amount for an Automation email.
    """

    direction: typing.Optional[AutomationWorkflowEmailDelayDirection] = pydantic.Field(default=None)
    """
    Whether the delay settings describe before or after the delay action of an Automation email.
    """

    full_description: typing.Optional[str] = pydantic.Field(default=None)
    """
    The user-friendly description of the delay and trigger action settings for an Automation email.
    """

    type: typing.Optional[AutomationWorkflowEmailDelayType] = pydantic.Field(default=None)
    """
    The type of delay for an Automation email.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
