# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .automation_workflow_email_trigger_settings_runtime import AutomationWorkflowEmailTriggerSettingsRuntime
from .automation_workflow_email_trigger_settings_workflow_type import AutomationWorkflowEmailTriggerSettingsWorkflowType


class AutomationWorkflowEmailTriggerSettings(UniversalBaseModel):
    """
    Available triggers for Automation workflows.
    """

    runtime: typing.Optional[AutomationWorkflowEmailTriggerSettingsRuntime] = pydantic.Field(default=None)
    """
    A workflow's runtime settings for an Automation.
    """

    workflow_emails_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of emails in the Automation workflow.
    """

    workflow_title: typing.Optional[str] = pydantic.Field(default=None)
    """
    The title of the workflow type.
    """

    workflow_type: AutomationWorkflowEmailTriggerSettingsWorkflowType = pydantic.Field()
    """
    The type of Automation workflow.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
