# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .automation_workflow_email_delay import AutomationWorkflowEmailDelay
from .automation_workflow_email_links_item import AutomationWorkflowEmailLinksItem
from .automation_workflow_email_recipients import AutomationWorkflowEmailRecipients
from .automation_workflow_email_report_summary import AutomationWorkflowEmailReportSummary
from .automation_workflow_email_settings import AutomationWorkflowEmailSettings
from .automation_workflow_email_social_card import AutomationWorkflowEmailSocialCard
from .automation_workflow_email_status import AutomationWorkflowEmailStatus
from .automation_workflow_email_tracking import AutomationWorkflowEmailTracking
from .automation_workflow_email_trigger_settings import AutomationWorkflowEmailTriggerSettings


class AutomationWorkflowEmail(UniversalBaseModel):
    """
    A summary of an individual Automation workflow email.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[AutomationWorkflowEmailLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    archive_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The link to the campaign's archive version in ISO 8601 format.
    """

    content_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    How the campaign's content is put together ('template', 'drag_and_drop', 'html', 'url').
    """

    create_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the campaign was created in ISO 8601 format.
    """

    delay: typing.Optional[AutomationWorkflowEmailDelay] = pydantic.Field(default=None)
    """
    The delay settings for an Automation email.
    """

    emails_sent: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of emails sent for this campaign.
    """

    has_logo_merge_tag: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Determines if the campaign contains the *|BRAND:LOGO|* merge tag.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A string that uniquely identifies the Automation email.
    """

    needs_block_refresh: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Determines if the automation email needs its blocks refreshed by opening the web-based campaign editor.
    """

    position: typing.Optional[int] = pydantic.Field(default=None)
    """
    The position of an Automation email in a workflow.
    """

    recipients: typing.Optional[AutomationWorkflowEmailRecipients] = pydantic.Field(default=None)
    """
    List settings for the campaign.
    """

    report_summary: typing.Optional[AutomationWorkflowEmailReportSummary] = pydantic.Field(default=None)
    """
    For sent campaigns, a summary of opens and clicks.
    """

    send_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
     The date and time a campaign was sent in ISO 8601 format
    """

    settings: typing.Optional[AutomationWorkflowEmailSettings] = pydantic.Field(default=None)
    """
    Settings for the campaign including the email subject, from name, and from email address.
    """

    social_card: typing.Optional[AutomationWorkflowEmailSocialCard] = pydantic.Field(default=None)
    """
    The preview for the campaign, rendered by social networks like Facebook and Twitter. [Learn more](https://mailchimp.com/help/enable-and-customize-social-cards/).
    """

    start_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the campaign was started in ISO 8601 format.
    """

    status: typing.Optional[AutomationWorkflowEmailStatus] = pydantic.Field(default=None)
    """
    The current status of the campaign.
    """

    tracking: typing.Optional[AutomationWorkflowEmailTracking] = pydantic.Field(default=None)
    """
    The tracking options for a campaign.
    """

    trigger_settings: typing.Optional[AutomationWorkflowEmailTriggerSettings] = pydantic.Field(default=None)
    """
    Available triggers for Automation workflows.
    """

    web_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    The ID used in the Mailchimp web application. View this automation in your Mailchimp account at `https://{dc}.admin.mailchimp.com/campaigns/show/?id={web_id}`.
    """

    workflow_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A string that uniquely identifies an Automation workflow.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
