# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .batch_completed_at import BatchCompletedAt
from .batch_links_item import BatchLinksItem
from .batch_status import BatchStatus


class Batch(UniversalBaseModel):
    """
    The status of a batch request
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[BatchLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    completed_at: typing.Optional[BatchCompletedAt] = pydantic.Field(default=None)
    """
    The date and time when all operations in the batch request completed in ISO 8601 format.
    """

    errored_operations: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of completed operations that returned an error.
    """

    finished_operations: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of completed operations. This includes operations that returned an error.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A string that uniquely identifies this batch request.
    """

    response_body_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL of the gzipped archive of the results of all the operations.
    """

    status: typing.Optional[BatchStatus] = pydantic.Field(default=None)
    """
    The status of the batch call. [Learn more](https://mailchimp.com/developer/marketing/guides/run-async-requests-batch-endpoint/#check-the-status-of-a-batch-operation) about the batch operation status.
    """

    submitted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time when the server received the batch request in ISO 8601 format.
    """

    total_operations: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of operations to complete as part of this batch request. For GET requests requiring pagination, each page counts as a separate operation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
