# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CampaignReportClicks(UniversalBaseModel):
    """
    An object describing the click activity for the campaign.
    """

    click_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    The number of unique clicks divided by the total number of successful deliveries.
    """

    clicks_total: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of clicks for the campaign.
    """

    last_click: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time of the last recorded click for the campaign in ISO 8601 format.
    """

    unique_clicks: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of unique clicks for links across a campaign.
    """

    unique_subscriber_clicks: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of subscribers who clicked on a campaign.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
