# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CampaignVariateSettingsCombinationsItem(UniversalBaseModel):
    content_description: typing.Optional[int] = pydantic.Field(default=None)
    """
    The index of `variate_settings.contents` used.
    """

    from_name: typing.Optional[int] = pydantic.Field(default=None)
    """
    The index of `variate_settings.from_names` used.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique ID for the combination.
    """

    recipients: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of recipients for this combination.
    """

    reply_to: typing.Optional[int] = pydantic.Field(default=None)
    """
    The index of `variate_settings.reply_to_addresses` used.
    """

    send_time: typing.Optional[int] = pydantic.Field(default=None)
    """
    The index of `variate_settings.send_times` used.
    """

    subject_line: typing.Optional[int] = pydantic.Field(default=None)
    """
    The index of `variate_settings.subject_lines` used.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
