# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CampaignReportIndustryStats(UniversalBaseModel):
    """
    The average campaign statistics for your industry.
    """

    abuse_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    The industry abuse rate.
    """

    bounce_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    The industry bounce rate.
    """

    click_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    The industry click rate.
    """

    open_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    The industry open rate.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of business industry associated with your account. For example: retail, education, etc.
    """

    unopen_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    The industry unopened rate.
    """

    unsub_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    The industry unsubscribe rate.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
