# This file was auto-generated by Fern from our API Definition.

import typing

CampaignsStatus = typing.Union[
    typing.Literal["save", "paused", "schedule", "sending", "sent", "canceled", "canceling", "archived"], typing.Any
]
