# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CampaignReportAbSplitB(UniversalBaseModel):
    """
    Stats for Campaign B.
    """

    abuse_reports: typing.Optional[int] = pydantic.Field(default=None)
    """
    Abuse reports for Campaign B.
    """

    bounces: typing.Optional[int] = pydantic.Field(default=None)
    """
    Bounces for Campaign B.
    """

    forwards: typing.Optional[int] = pydantic.Field(default=None)
    """
    Forwards for Campaign B.
    """

    forwards_opens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Opens for forwards from Campaign B.
    """

    last_open: typing.Optional[str] = pydantic.Field(default=None)
    """
    The last open for Campaign B.
    """

    opens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Opens for Campaign B.
    """

    recipient_clicks: typing.Optional[int] = pydantic.Field(default=None)
    """
    Recipients clicks for Campaign B.
    """

    unique_opens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Unique opens for Campaign B.
    """

    unsubs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Unsubscribes for Campaign B.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
