# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .campaigns_rss_opts_frequency import CampaignsRssOptsFrequency
from .campaigns_rss_opts_schedule import CampaignsRssOptsSchedule


class CampaignsRssOpts(UniversalBaseModel):
    """
    [RSS](https://mailchimp.com/help/share-your-blog-posts-with-mailchimp/) options for a campaign.
    """

    constrain_rss_img: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to add CSS to images in the RSS feed to constrain their width in campaigns.
    """

    feed_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL for the RSS feed.
    """

    frequency: typing.Optional[CampaignsRssOptsFrequency] = pydantic.Field(default=None)
    """
    The frequency of the RSS Campaign.
    """

    last_sent: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date the campaign was last sent.
    """

    schedule: typing.Optional[CampaignsRssOptsSchedule] = pydantic.Field(default=None)
    """
    The schedule for sending the RSS Campaign.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
