# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CampaignsSocialCard(UniversalBaseModel):
    """
    The preview for the campaign, rendered by social networks like Facebook and Twitter. [Learn more](https://mailchimp.com/help/enable-and-customize-social-cards/).
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    A short summary of the campaign to display.
    """

    image_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The url for the header image for the card.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    The title for the card. Typically the subject line of the campaign.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
