# This file was auto-generated by Fern from our API Definition.

import typing

CampaignDeliveryStatusStatus = typing.Union[
    typing.Literal["delivering", "delivered", "canceling", "canceled"], typing.Any
]
