# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ClickDetailReportAbSplitB(UniversalBaseModel):
    """
    Stats for Group B.
    """

    click_percentage_b: typing.Optional[float] = pydantic.Field(default=None)
    """
    The percentage of total clicks for Group B.
    """

    total_clicks_b: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of clicks for Group B.
    """

    unique_click_percentage_b: typing.Optional[float] = pydantic.Field(default=None)
    """
    The percentage of unique clicks for Group B.
    """

    unique_clicks_b: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of unique clicks for Group B.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
