# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .conversation_last_message import ConversationLastMessage
from .conversation_links_item import ConversationLinksItem


class Conversation(UniversalBaseModel):
    """
    Details about an individual conversation. Conversation tracking is a feature available to paid accounts that lets you view replies to your campaigns in your Mailchimp account.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[ConversationLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    campaign_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the campaign for this conversation.
    """

    from_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    A label representing the email of the sender of this message.
    """

    from_label: typing.Optional[str] = pydantic.Field(default=None)
    """
    A label representing the sender of this message.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A string that uniquely identifies this conversation.
    """

    last_message: typing.Optional[ConversationLastMessage] = pydantic.Field(default=None)
    """
    The most recent message in the conversation.
    """

    list_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the list for this conversation.
    """

    message_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of messages in this conversation.
    """

    subject: typing.Optional[str] = pydantic.Field(default=None)
    """
    The subject of the message.
    """

    unread_messages: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of unread messages in this conversation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
