# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ECommerceOrderBillingAddress(UniversalBaseModel):
    """
    The billing address for the order.
    """

    address1: typing.Optional[str] = pydantic.Field(default=None)
    """
    The billing address for the order.
    """

    address2: typing.Optional[str] = pydantic.Field(default=None)
    """
    An additional field for the billing address.
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    The city in the billing address.
    """

    company: typing.Optional[str] = pydantic.Field(default=None)
    """
    The company associated with the billing address.
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    The country in the billing address.
    """

    country_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The two-letter code for the country in the billing address.
    """

    latitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    The latitude for the billing address location.
    """

    longitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    The longitude for the billing address location.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name associated with an order's billing address.
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    The phone number for the billing address.
    """

    postal_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The postal or zip code in the billing address.
    """

    province: typing.Optional[str] = pydantic.Field(default=None)
    """
    The state or normalized province in the billing address.
    """

    province_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The two-letter code for the province or state in the billing address.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
