# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .e_commerce_customer import ECommerceCustomer
from .e_commerce_order_billing_address import ECommerceOrderBillingAddress
from .e_commerce_order_line_item import ECommerceOrderLineItem
from .e_commerce_order_links_item import ECommerceOrderLinksItem
from .e_commerce_order_order_total import ECommerceOrderOrderTotal
from .e_commerce_order_outreach import ECommerceOrderOutreach
from .e_commerce_order_promos_item import ECommerceOrderPromosItem
from .e_commerce_order_shipping_address import ECommerceOrderShippingAddress
from .e_commerce_order_shipping_total import ECommerceOrderShippingTotal
from .e_commerce_order_tax_total import ECommerceOrderTaxTotal
from .e_commerce_order_tracking_code import ECommerceOrderTrackingCode


class ECommerceOrder(UniversalBaseModel):
    """
    Information about a specific order.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[ECommerceOrderLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    billing_address: typing.Optional[ECommerceOrderBillingAddress] = pydantic.Field(default=None)
    """
    The billing address for the order.
    """

    campaign_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A string that uniquely identifies the campaign associated with an order.
    """

    cart_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A cart id that the order was placed for.
    """

    cancelled_at_foreign: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the order was cancelled in ISO 8601 format.
    """

    currency_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The three-letter ISO 4217 code for the currency that the store accepts.
    """

    customer: typing.Optional[ECommerceCustomer] = None
    discount_total: typing.Optional[float] = pydantic.Field(default=None)
    """
    The total amount of the discounts to be applied to the price of the order.
    """

    financial_status: typing.Optional[str] = pydantic.Field(default=None)
    """
    The order status. Use this parameter to trigger [Order Notifications](https://mailchimp.com/developer/marketing/docs/e-commerce/#order-notifications).
    """

    fulfillment_status: typing.Optional[str] = pydantic.Field(default=None)
    """
    The fulfillment status for the order. Use this parameter to trigger [Order Notifications](https://mailchimp.com/developer/marketing/docs/e-commerce/#order-notifications).
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique identifier for the order.
    """

    landing_site: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL for the page where the buyer landed when entering the shop.
    """

    lines: typing.Optional[typing.List[ECommerceOrderLineItem]] = pydantic.Field(default=None)
    """
    An array of the order's line items.
    """

    order_total: typing.Optional[ECommerceOrderOrderTotal] = None
    order_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL for the order.
    """

    outreach: typing.Optional[ECommerceOrderOutreach] = pydantic.Field(default=None)
    """
    The outreach associated with this order. For example, an email campaign or Facebook ad.
    """

    processed_at_foreign: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the order was processed in ISO 8601 format.
    """

    promos: typing.Optional[typing.List[ECommerceOrderPromosItem]] = pydantic.Field(default=None)
    """
    The promo codes applied on the order
    """

    shipping_address: typing.Optional[ECommerceOrderShippingAddress] = pydantic.Field(default=None)
    """
    The shipping address for the order.
    """

    shipping_total: typing.Optional[ECommerceOrderShippingTotal] = None
    store_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier for the store.
    """

    tax_total: typing.Optional[ECommerceOrderTaxTotal] = None
    tracking_carrier: typing.Optional[str] = pydantic.Field(default=None)
    """
    The tracking carrier associated with the order.
    """

    tracking_code: typing.Optional[ECommerceOrderTrackingCode] = pydantic.Field(default=None)
    """
    The Mailchimp tracking code for the order. Uses the 'mc_tc' parameter in E-Commerce tracking URLs.
    """

    tracking_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    The tracking number associated with the order.
    """

    tracking_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The tracking URL associated with the order.
    """

    updated_at_foreign: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the order was updated in ISO 8601 format.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
