# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ECommerceOrderOutreach(UniversalBaseModel):
    """
    The outreach associated with this order. For example, an email campaign or Facebook ad.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique identifier for the outreach. Can be an email campaign ID.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name for the outreach.
    """

    published_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the Outreach was published in ISO 8601 format.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of the outreach.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
