# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .facebook_ad_recipients import FacebookAdRecipients
from .facebook_ad_report_summary import FacebookAdReportSummary
from .facebook_ad_status import FacebookAdStatus
from .facebook_ad_type import FacebookAdType


class FacebookAd(UniversalBaseModel):
    canceled_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the outreach was canceled in ISO 8601 format.
    """

    create_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the outreach was created in ISO 8601 format.
    """

    has_segment: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If this outreach targets a segment of your audience.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique ID of an Outreach.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Title or name of an Outreach.
    """

    published_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the outreach was (or will be) published in ISO 8601 format.
    """

    recipients: typing.Optional[FacebookAdRecipients] = pydantic.Field(default=None)
    """
    High level audience information for who the outreach targets.
    """

    report_summary: typing.Optional[FacebookAdReportSummary] = pydantic.Field(default=None)
    """
    High level reporting stats for an outreach.
    """

    show_report: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Outreach report availability. Note: This property is hotly debated in what it _should_ convey. See [MCP-1371](https://jira.mailchimp.com/browse/MCP-1371) for more context.
    """

    start_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the outreach was started in ISO 8601 format.
    """

    status: typing.Optional[FacebookAdStatus] = pydantic.Field(default=None)
    """
    The status of this outreach.
    """

    type: typing.Optional[FacebookAdType] = pydantic.Field(default=None)
    """
    The type of outreach this object is.
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the outreach was last updated in ISO 8601 format.
    """

    web_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    The ID used in the Mailchimp web application. For example, for a `regular` outreach, you can view this campaign in your Mailchimp account at `https://{dc}.admin.mailchimp.com/campaigns/show/?id={web_id}`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
