# This file was auto-generated by Fern from our API Definition.

import typing

FacebookAdStatus = typing.Union[
    typing.Literal[
        "save",
        "paused",
        "schedule",
        "scheduled",
        "sending",
        "sent",
        "canceled",
        "canceling",
        "active",
        "disconnected",
        "somepaused",
        "draft",
        "completed",
        "partialRejected",
        "pending",
        "rejected",
        "published",
        "unpublished",
    ],
    typing.Any,
]
