# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .growth_history_links_item import GrowthHistoryLinksItem


class GrowthHistory(UniversalBaseModel):
    """
    A summary of a specific list's growth activity for a specific month and year.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[GrowthHistoryLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    cleaned: typing.Optional[int] = pydantic.Field(default=None)
    """
    Newly cleaned (hard-bounced) members on the list for a specific month.
    """

    deleted: typing.Optional[int] = pydantic.Field(default=None)
    """
    Newly deleted members on the list for a specific month.
    """

    existing: typing.Optional[int] = pydantic.Field(default=None)
    """
    (deprecated)
    """

    imports: typing.Optional[int] = pydantic.Field(default=None)
    """
    (deprecated)
    """

    list_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The list id for the growth activity report.
    """

    month: typing.Optional[str] = pydantic.Field(default=None)
    """
    The month that the growth history is describing.
    """

    optins: typing.Optional[int] = pydantic.Field(default=None)
    """
    (deprecated)
    """

    pending: typing.Optional[int] = pydantic.Field(default=None)
    """
    Pending members on the list for a specific month.
    """

    reconfirm: typing.Optional[int] = pydantic.Field(default=None)
    """
    Newly reconfirmed members on the list for a specific month.
    """

    subscribed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total subscribed members on the list at the end of the month.
    """

    transactional: typing.Optional[int] = pydantic.Field(default=None)
    """
    Subscribers that have been sent transactional emails via Mandrill.
    """

    unsubscribed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Newly unsubscribed members on the list for a specific month.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
