# This file was auto-generated by Fern from our API Definition.

import typing

InterestLinksItemMethod = typing.Union[
    typing.Literal["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"], typing.Any
]
