# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListMembersLastNote(UniversalBaseModel):
    """
    The most recent Note added about this member.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the note was created in ISO 8601 format.
    """

    created_by: typing.Optional[str] = pydantic.Field(default=None)
    """
    The author of the note.
    """

    note: typing.Optional[str] = pydantic.Field(default=None)
    """
    The content of the note.
    """

    note_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    The note id.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
