# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .merge_field_links_item import MergeFieldLinksItem
from .merge_field_options import MergeFieldOptions
from .merge_field_type import MergeFieldType


class MergeField(UniversalBaseModel):
    """
    A [merge field](https://mailchimp.com/developer/marketing/docs/merge-fields/) for an audience.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[MergeFieldLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    default_value: typing.Optional[str] = pydantic.Field(default=None)
    """
    The default value for the merge field if `null`.
    """

    display_order: typing.Optional[int] = pydantic.Field(default=None)
    """
    The order that the merge field displays on the list signup form.
    """

    help_text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Extra text to help the subscriber fill out the form.
    """

    list_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID that identifies this merge field's audience'.
    """

    merge_field_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    The maximum number of merge fields this audience can hold. The limit is determined by the account's plan. Returned on POST responses only. Subtract `total_items` from this value to derive the remaining capacity.
    """

    merge_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    An unchanging id for the merge field.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the merge field (audience field).
    """

    options: typing.Optional[MergeFieldOptions] = pydantic.Field(default=None)
    """
    Extra options for some merge field types.
    """

    public: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the merge field is displayed on the signup form.
    """

    required: typing.Optional[bool] = pydantic.Field(default=None)
    """
    The boolean value if the merge field is required.
    """

    tag: typing.Optional[str] = pydantic.Field(default=None)
    """
    The merge tag used for Mailchimp campaigns and [adding contact information](https://mailchimp.com/developer/marketing/docs/merge-fields/#add-merge-data-to-contacts).
    """

    total_items: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of merge fields on the audience after this field was created. Returned on POST responses only.
    """

    type: typing.Optional[MergeFieldType] = pydantic.Field(default=None)
    """
    The [type](https://mailchimp.com/developer/marketing/docs/merge-fields/#structure) for the merge field.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
