# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OpenActivityOpensItem(UniversalBaseModel):
    """
    A summary of the interaction with the campaign.
    """

    is_proxy_open: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates if the open was from an email client that use proxies.
    """

    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time recorded for the action in ISO 8601 format.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
