# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ReportingFacebookAdChannel(UniversalBaseModel):
    """
    Channel settings
    """

    fb_placement_audience: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Is this for facebook audience
    """

    fb_placement_feed: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Is this for facebook feed
    """

    ig_placement_feed: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Is this for instagram feed
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
