# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .facebook_ad_recipients import FacebookAdRecipients
from .facebook_ad_status import FacebookAdStatus
from .facebook_ad_type import FacebookAdType
from .reporting_facebook_ad_audience import ReportingFacebookAdAudience
from .reporting_facebook_ad_audience_activity import ReportingFacebookAdAudienceActivity
from .reporting_facebook_ad_budget import ReportingFacebookAdBudget
from .reporting_facebook_ad_channel import ReportingFacebookAdChannel
from .reporting_facebook_ad_links_item import ReportingFacebookAdLinksItem
from .reporting_facebook_ad_report_summary import ReportingFacebookAdReportSummary


class ReportingFacebookAd(UniversalBaseModel):
    email_source_name: typing.Optional[str] = None
    end_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the ad was ended in ISO 8601 format.
    """

    needs_attention: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If the ad has a problem and needs attention.
    """

    paused_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the ad was paused in ISO 8601 format.
    """

    thumbnail: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL of the thumbnail for this outreach.
    """

    was_canceled_by_facebook: typing.Optional[bool] = None
    audience: typing.Optional[ReportingFacebookAdAudience] = pydantic.Field(default=None)
    """
    Audience settings
    """

    audience_activity: typing.Optional[ReportingFacebookAdAudienceActivity] = None
    budget: typing.Optional[ReportingFacebookAdBudget] = None
    channel: typing.Optional[ReportingFacebookAdChannel] = pydantic.Field(default=None)
    """
    Channel settings
    """

    report_summary: typing.Optional[ReportingFacebookAdReportSummary] = pydantic.Field(default=None)
    """
    Report summary of facebook ad
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[ReportingFacebookAdLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    canceled_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the outreach was canceled in ISO 8601 format.
    """

    create_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the outreach was created in ISO 8601 format.
    """

    has_segment: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If this outreach targets a segment of your audience.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique ID of an Outreach.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Title or name of an Outreach.
    """

    published_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the outreach was (or will be) published in ISO 8601 format.
    """

    recipients: typing.Optional[FacebookAdRecipients] = pydantic.Field(default=None)
    """
    High level audience information for who the outreach targets.
    """

    show_report: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Outreach report availability. Note: This property is hotly debated in what it _should_ convey. See [MCP-1371](https://jira.mailchimp.com/browse/MCP-1371) for more context.
    """

    start_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the outreach was started in ISO 8601 format.
    """

    status: typing.Optional[FacebookAdStatus] = pydantic.Field(default=None)
    """
    The status of this outreach.
    """

    type: typing.Optional[FacebookAdType] = pydantic.Field(default=None)
    """
    The type of outreach this object is.
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time the outreach was last updated in ISO 8601 format.
    """

    web_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    The ID used in the Mailchimp web application. For example, for a `regular` outreach, you can view this campaign in your Mailchimp account at `https://{dc}.admin.mailchimp.com/campaigns/show/?id={web_id}`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
