# This file was auto-generated by Fern from our API Definition.

import typing

ReportingFacebookAdAudienceType = typing.Union[
    typing.Literal["Custom Audience", "Lookalike Audience", "Interest-based Audience"], typing.Any
]
