# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_ecomm_number_field import SegmentTypeItemEcommNumberField
from .segment_type_item_ecomm_number_op import SegmentTypeItemEcommNumberOp
from .segment_type_item_ecomm_number_value import SegmentTypeItemEcommNumberValue


class SegmentTypeItemEcommNumber(UniversalBaseModel):
    """
    Segment by average spent total, number of orders, total number of products purchased, or average number of products per order.
    """

    field: SegmentTypeItemEcommNumberField = pydantic.Field()
    """
    Segment by average spent total, number of orders, total number of products purchased, or average number of products per order.
    """

    op: SegmentTypeItemEcommNumberOp = pydantic.Field()
    """
    Members who have spent exactly, have not spent exactly, spent more, or spent less than the segment value.
    """

    value: SegmentTypeItemEcommNumberValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
