# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_member_rating_field import SegmentTypeItemMemberRatingField
from .segment_type_item_member_rating_op import SegmentTypeItemMemberRatingOp
from .segment_type_item_member_rating_value import SegmentTypeItemMemberRatingValue


class SegmentTypeItemMemberRating(UniversalBaseModel):
    """
    Segment by member rating.
    """

    field: SegmentTypeItemMemberRatingField = pydantic.Field()
    """
    Segment by member rating.
    """

    op: SegmentTypeItemMemberRatingOp = pydantic.Field()
    """
    Members who have have a rating that is/not exactly a given number or members who have a rating greater/less than a given number.
    """

    value: SegmentTypeItemMemberRatingValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
