# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_fuzzy_segment_field import SegmentTypeItemFuzzySegmentField
from .segment_type_item_fuzzy_segment_op import SegmentTypeItemFuzzySegmentOp
from .segment_type_item_fuzzy_segment_value import SegmentTypeItemFuzzySegmentValue


class SegmentTypeItemFuzzySegment(UniversalBaseModel):
    """
    Segment by similar subscribers.
    """

    field: SegmentTypeItemFuzzySegmentField = pydantic.Field()
    """
    Segment by similar subscribers.
    """

    op: SegmentTypeItemFuzzySegmentOp = pydantic.Field()
    """
    Members who are/are not apart of a 'similar subscribers' segment.
    """

    value: SegmentTypeItemFuzzySegmentValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
