# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_text_merge_op import SegmentTypeItemTextMergeOp


class SegmentTypeItemTextMerge(UniversalBaseModel):
    """
    Segment by a given text or number merge field.
    """

    field: str = pydantic.Field()
    """
    A text or number merge field to segment.
    """

    op: SegmentTypeItemTextMergeOp = pydantic.Field()
    """
    Whether the member's merge information is/is not, contains/does not contain, starts/ends with, or is greater/less than a value
    """

    value: typing.Optional[str] = pydantic.Field(default=None)
    """
    The value to segment a text or number merge field with.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
