# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_aim_field import SegmentTypeItemAimField
from .segment_type_item_aim_op import SegmentTypeItemAimOp


class SegmentTypeItemAim(UniversalBaseModel):
    """
    Segment by interaction with a specific campaign.
    """

    field: typing.Optional[SegmentTypeItemAimField] = pydantic.Field(default=None)
    """
    Segment by interaction with a specific campaign.
    """

    op: typing.Optional[SegmentTypeItemAimOp] = pydantic.Field(default=None)
    """
    The status of the member with regard to their campaign interaction. One of the following: opened, clicked, was sent, didn't open, didn't click, or was not sent.
    """

    value: typing.Optional[str] = pydantic.Field(default=None)
    """
    Either the web id value for a specific campaign or 'any' to account for subscribers who have/have not interacted with any campaigns.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
