# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_address_merge_op import SegmentTypeItemAddressMergeOp
from .segment_type_item_aim_field import SegmentTypeItemAimField
from .segment_type_item_aim_op import SegmentTypeItemAimOp
from .segment_type_item_automation_field import SegmentTypeItemAutomationField
from .segment_type_item_automation_op import SegmentTypeItemAutomationOp
from .segment_type_item_birthday_merge_op import SegmentTypeItemBirthdayMergeOp
from .segment_type_item_campaign_poll_field import SegmentTypeItemCampaignPollField
from .segment_type_item_campaign_poll_op import SegmentTypeItemCampaignPollOp
from .segment_type_item_conversation_field import SegmentTypeItemConversationField
from .segment_type_item_conversation_op import SegmentTypeItemConversationOp
from .segment_type_item_date_field import SegmentTypeItemDateField
from .segment_type_item_date_merge_op import SegmentTypeItemDateMergeOp
from .segment_type_item_date_op import SegmentTypeItemDateOp
from .segment_type_item_ecomm_category_field import SegmentTypeItemEcommCategoryField
from .segment_type_item_ecomm_category_op import SegmentTypeItemEcommCategoryOp
from .segment_type_item_ecomm_number_field import SegmentTypeItemEcommNumberField
from .segment_type_item_ecomm_number_op import SegmentTypeItemEcommNumberOp
from .segment_type_item_ecomm_number_value import SegmentTypeItemEcommNumberValue
from .segment_type_item_ecomm_purchased_field import SegmentTypeItemEcommPurchasedField
from .segment_type_item_ecomm_purchased_op import SegmentTypeItemEcommPurchasedOp
from .segment_type_item_ecomm_spent_field import SegmentTypeItemEcommSpentField
from .segment_type_item_ecomm_spent_op import SegmentTypeItemEcommSpentOp
from .segment_type_item_ecomm_spent_value import SegmentTypeItemEcommSpentValue
from .segment_type_item_ecomm_store_field import SegmentTypeItemEcommStoreField
from .segment_type_item_ecomm_store_op import SegmentTypeItemEcommStoreOp
from .segment_type_item_email_address_field import SegmentTypeItemEmailAddressField
from .segment_type_item_email_address_op import SegmentTypeItemEmailAddressOp
from .segment_type_item_email_client_field import SegmentTypeItemEmailClientField
from .segment_type_item_email_client_op import SegmentTypeItemEmailClientOp
from .segment_type_item_fuzzy_segment_field import SegmentTypeItemFuzzySegmentField
from .segment_type_item_fuzzy_segment_op import SegmentTypeItemFuzzySegmentOp
from .segment_type_item_fuzzy_segment_value import SegmentTypeItemFuzzySegmentValue
from .segment_type_item_goal_activity_field import SegmentTypeItemGoalActivityField
from .segment_type_item_goal_activity_op import SegmentTypeItemGoalActivityOp
from .segment_type_item_goal_timestamp_field import SegmentTypeItemGoalTimestampField
from .segment_type_item_goal_timestamp_op import SegmentTypeItemGoalTimestampOp
from .segment_type_item_interests_op import SegmentTypeItemInterestsOp
from .segment_type_item_ip_geo_country_state_field import SegmentTypeItemIpGeoCountryStateField
from .segment_type_item_ip_geo_country_state_op import SegmentTypeItemIpGeoCountryStateOp
from .segment_type_item_ip_geo_in_field import SegmentTypeItemIpGeoInField
from .segment_type_item_ip_geo_in_op import SegmentTypeItemIpGeoInOp
from .segment_type_item_ip_geo_in_zip_field import SegmentTypeItemIpGeoInZipField
from .segment_type_item_ip_geo_in_zip_op import SegmentTypeItemIpGeoInZipOp
from .segment_type_item_ip_geo_unknown_field import SegmentTypeItemIpGeoUnknownField
from .segment_type_item_ip_geo_unknown_op import SegmentTypeItemIpGeoUnknownOp
from .segment_type_item_ip_geo_zip_field import SegmentTypeItemIpGeoZipField
from .segment_type_item_ip_geo_zip_op import SegmentTypeItemIpGeoZipOp
from .segment_type_item_language_field import SegmentTypeItemLanguageField
from .segment_type_item_language_op import SegmentTypeItemLanguageOp
from .segment_type_item_member_rating_field import SegmentTypeItemMemberRatingField
from .segment_type_item_member_rating_op import SegmentTypeItemMemberRatingOp
from .segment_type_item_member_rating_value import SegmentTypeItemMemberRatingValue
from .segment_type_item_new_subscribers_field import SegmentTypeItemNewSubscribersField
from .segment_type_item_new_subscribers_op import SegmentTypeItemNewSubscribersOp
from .segment_type_item_predicted_age_field import SegmentTypeItemPredictedAgeField
from .segment_type_item_predicted_age_op import SegmentTypeItemPredictedAgeOp
from .segment_type_item_predicted_age_value import SegmentTypeItemPredictedAgeValue
from .segment_type_item_predicted_gender_field import SegmentTypeItemPredictedGenderField
from .segment_type_item_predicted_gender_op import SegmentTypeItemPredictedGenderOp
from .segment_type_item_predicted_gender_value import SegmentTypeItemPredictedGenderValue
from .segment_type_item_select_merge_op import SegmentTypeItemSelectMergeOp
from .segment_type_item_signup_source_field import SegmentTypeItemSignupSourceField
from .segment_type_item_signup_source_op import SegmentTypeItemSignupSourceOp
from .segment_type_item_social_age_field import SegmentTypeItemSocialAgeField
from .segment_type_item_social_age_op import SegmentTypeItemSocialAgeOp
from .segment_type_item_social_age_value import SegmentTypeItemSocialAgeValue
from .segment_type_item_social_gender_field import SegmentTypeItemSocialGenderField
from .segment_type_item_social_gender_op import SegmentTypeItemSocialGenderOp
from .segment_type_item_social_gender_value import SegmentTypeItemSocialGenderValue
from .segment_type_item_social_influence_field import SegmentTypeItemSocialInfluenceField
from .segment_type_item_social_influence_op import SegmentTypeItemSocialInfluenceOp
from .segment_type_item_social_network_follow_field import SegmentTypeItemSocialNetworkFollowField
from .segment_type_item_social_network_follow_op import SegmentTypeItemSocialNetworkFollowOp
from .segment_type_item_social_network_follow_value import SegmentTypeItemSocialNetworkFollowValue
from .segment_type_item_social_network_member_field import SegmentTypeItemSocialNetworkMemberField
from .segment_type_item_social_network_member_op import SegmentTypeItemSocialNetworkMemberOp
from .segment_type_item_social_network_member_value import SegmentTypeItemSocialNetworkMemberValue
from .segment_type_item_static_segment_field import SegmentTypeItemStaticSegmentField
from .segment_type_item_static_segment_op import SegmentTypeItemStaticSegmentOp
from .segment_type_item_static_segment_value import SegmentTypeItemStaticSegmentValue
from .segment_type_item_survey_monkey_field import SegmentTypeItemSurveyMonkeyField
from .segment_type_item_survey_monkey_op import SegmentTypeItemSurveyMonkeyOp
from .segment_type_item_text_merge_op import SegmentTypeItemTextMergeOp
from .segment_type_item_vip_field import SegmentTypeItemVipField
from .segment_type_item_vip_op import SegmentTypeItemVipOp
from .segment_type_item_zip_merge_op import SegmentTypeItemZipMergeOp


class SegmentTypeItem_Aim(UniversalBaseModel):
    condition_type: typing.Literal["Aim"] = "Aim"
    field: typing.Optional[SegmentTypeItemAimField] = None
    op: typing.Optional[SegmentTypeItemAimOp] = None
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_Automation(UniversalBaseModel):
    condition_type: typing.Literal["Automation"] = "Automation"
    field: SegmentTypeItemAutomationField
    op: SegmentTypeItemAutomationOp
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_CampaignPoll(UniversalBaseModel):
    condition_type: typing.Literal["CampaignPoll"] = "CampaignPoll"
    field: SegmentTypeItemCampaignPollField
    op: SegmentTypeItemCampaignPollOp
    value: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_Conversation(UniversalBaseModel):
    condition_type: typing.Literal["Conversation"] = "Conversation"
    field: SegmentTypeItemConversationField
    op: SegmentTypeItemConversationOp
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_Date(UniversalBaseModel):
    condition_type: typing.Literal["Date"] = "Date"
    extra: typing.Optional[str] = None
    field: SegmentTypeItemDateField
    op: SegmentTypeItemDateOp
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_EmailClient(UniversalBaseModel):
    condition_type: typing.Literal["EmailClient"] = "EmailClient"
    field: SegmentTypeItemEmailClientField
    op: SegmentTypeItemEmailClientOp
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_Language(UniversalBaseModel):
    condition_type: typing.Literal["Language"] = "Language"
    field: SegmentTypeItemLanguageField
    op: SegmentTypeItemLanguageOp
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_MemberRating(UniversalBaseModel):
    condition_type: typing.Literal["MemberRating"] = "MemberRating"
    field: SegmentTypeItemMemberRatingField
    op: SegmentTypeItemMemberRatingOp
    value: SegmentTypeItemMemberRatingValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_SignupSource(UniversalBaseModel):
    condition_type: typing.Literal["SignupSource"] = "SignupSource"
    field: SegmentTypeItemSignupSourceField
    op: SegmentTypeItemSignupSourceOp
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_SurveyMonkey(UniversalBaseModel):
    condition_type: typing.Literal["SurveyMonkey"] = "SurveyMonkey"
    field: SegmentTypeItemSurveyMonkeyField
    op: SegmentTypeItemSurveyMonkeyOp
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_Vip(UniversalBaseModel):
    condition_type: typing.Literal["VIP"] = "VIP"
    field: SegmentTypeItemVipField
    op: SegmentTypeItemVipOp

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_Interests(UniversalBaseModel):
    condition_type: typing.Literal["Interests"] = "Interests"
    field: typing.Optional[str] = None
    op: typing.Optional[SegmentTypeItemInterestsOp] = None
    value: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_EcommCategory(UniversalBaseModel):
    condition_type: typing.Literal["EcommCategory"] = "EcommCategory"
    field: typing.Optional[SegmentTypeItemEcommCategoryField] = None
    op: typing.Optional[SegmentTypeItemEcommCategoryOp] = None
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_EcommNumber(UniversalBaseModel):
    condition_type: typing.Literal["EcommNumber"] = "EcommNumber"
    field: SegmentTypeItemEcommNumberField
    op: SegmentTypeItemEcommNumberOp
    value: SegmentTypeItemEcommNumberValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_EcommPurchased(UniversalBaseModel):
    condition_type: typing.Literal["EcommPurchased"] = "EcommPurchased"
    field: typing.Optional[SegmentTypeItemEcommPurchasedField] = None
    op: typing.Optional[SegmentTypeItemEcommPurchasedOp] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_EcommSpent(UniversalBaseModel):
    condition_type: typing.Literal["EcommSpent"] = "EcommSpent"
    field: typing.Optional[SegmentTypeItemEcommSpentField] = None
    op: typing.Optional[SegmentTypeItemEcommSpentOp] = None
    value: typing.Optional[SegmentTypeItemEcommSpentValue] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_EcommStore(UniversalBaseModel):
    condition_type: typing.Literal["EcommStore"] = "EcommStore"
    field: typing.Optional[SegmentTypeItemEcommStoreField] = None
    op: typing.Optional[SegmentTypeItemEcommStoreOp] = None
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_GoalActivity(UniversalBaseModel):
    condition_type: typing.Literal["GoalActivity"] = "GoalActivity"
    field: SegmentTypeItemGoalActivityField
    op: SegmentTypeItemGoalActivityOp
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_GoalTimestamp(UniversalBaseModel):
    condition_type: typing.Literal["GoalTimestamp"] = "GoalTimestamp"
    field: SegmentTypeItemGoalTimestampField
    op: SegmentTypeItemGoalTimestampOp
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_FuzzySegment(UniversalBaseModel):
    condition_type: typing.Literal["FuzzySegment"] = "FuzzySegment"
    field: SegmentTypeItemFuzzySegmentField
    op: SegmentTypeItemFuzzySegmentOp
    value: SegmentTypeItemFuzzySegmentValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_StaticSegment(UniversalBaseModel):
    condition_type: typing.Literal["StaticSegment"] = "StaticSegment"
    field: SegmentTypeItemStaticSegmentField
    op: SegmentTypeItemStaticSegmentOp
    value: SegmentTypeItemStaticSegmentValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_IpGeoCountryState(UniversalBaseModel):
    condition_type: typing.Literal["IPGeoCountryState"] = "IPGeoCountryState"
    field: SegmentTypeItemIpGeoCountryStateField
    op: SegmentTypeItemIpGeoCountryStateOp
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_IpGeoIn(UniversalBaseModel):
    condition_type: typing.Literal["IPGeoIn"] = "IPGeoIn"
    addr: str
    field: SegmentTypeItemIpGeoInField
    lat: str
    lng: str
    op: SegmentTypeItemIpGeoInOp
    value: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_IpGeoInZip(UniversalBaseModel):
    condition_type: typing.Literal["IPGeoInZip"] = "IPGeoInZip"
    extra: int
    field: SegmentTypeItemIpGeoInZipField
    op: SegmentTypeItemIpGeoInZipOp
    value: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_IpGeoUnknown(UniversalBaseModel):
    condition_type: typing.Literal["IPGeoUnknown"] = "IPGeoUnknown"
    field: SegmentTypeItemIpGeoUnknownField
    op: SegmentTypeItemIpGeoUnknownOp

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_IpGeoZip(UniversalBaseModel):
    condition_type: typing.Literal["IPGeoZip"] = "IPGeoZip"
    field: SegmentTypeItemIpGeoZipField
    op: SegmentTypeItemIpGeoZipOp
    value: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_SocialAge(UniversalBaseModel):
    condition_type: typing.Literal["SocialAge"] = "SocialAge"
    field: SegmentTypeItemSocialAgeField
    op: SegmentTypeItemSocialAgeOp
    value: SegmentTypeItemSocialAgeValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_SocialGender(UniversalBaseModel):
    condition_type: typing.Literal["SocialGender"] = "SocialGender"
    field: SegmentTypeItemSocialGenderField
    op: SegmentTypeItemSocialGenderOp
    value: SegmentTypeItemSocialGenderValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_SocialInfluence(UniversalBaseModel):
    condition_type: typing.Literal["SocialInfluence"] = "SocialInfluence"
    field: SegmentTypeItemSocialInfluenceField
    op: SegmentTypeItemSocialInfluenceOp
    value: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_SocialNetworkMember(UniversalBaseModel):
    condition_type: typing.Literal["SocialNetworkMember"] = "SocialNetworkMember"
    field: SegmentTypeItemSocialNetworkMemberField
    op: SegmentTypeItemSocialNetworkMemberOp
    value: SegmentTypeItemSocialNetworkMemberValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_SocialNetworkFollow(UniversalBaseModel):
    condition_type: typing.Literal["SocialNetworkFollow"] = "SocialNetworkFollow"
    field: SegmentTypeItemSocialNetworkFollowField
    op: SegmentTypeItemSocialNetworkFollowOp
    value: SegmentTypeItemSocialNetworkFollowValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_AddressMerge(UniversalBaseModel):
    condition_type: typing.Literal["AddressMerge"] = "AddressMerge"
    field: str
    op: SegmentTypeItemAddressMergeOp
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_ZipMerge(UniversalBaseModel):
    condition_type: typing.Literal["ZipMerge"] = "ZipMerge"
    extra: str
    field: str
    op: SegmentTypeItemZipMergeOp
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_BirthdayMerge(UniversalBaseModel):
    condition_type: typing.Literal["BirthdayMerge"] = "BirthdayMerge"
    field: str
    op: SegmentTypeItemBirthdayMergeOp
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_DateMerge(UniversalBaseModel):
    condition_type: typing.Literal["DateMerge"] = "DateMerge"
    field: str
    op: SegmentTypeItemDateMergeOp
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_SelectMerge(UniversalBaseModel):
    condition_type: typing.Literal["SelectMerge"] = "SelectMerge"
    field: str
    op: SegmentTypeItemSelectMergeOp
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_TextMerge(UniversalBaseModel):
    condition_type: typing.Literal["TextMerge"] = "TextMerge"
    field: str
    op: SegmentTypeItemTextMergeOp
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_EmailAddress(UniversalBaseModel):
    condition_type: typing.Literal["EmailAddress"] = "EmailAddress"
    field: SegmentTypeItemEmailAddressField
    op: SegmentTypeItemEmailAddressOp
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_PredictedGender(UniversalBaseModel):
    condition_type: typing.Literal["PredictedGender"] = "PredictedGender"
    field: SegmentTypeItemPredictedGenderField
    op: SegmentTypeItemPredictedGenderOp
    value: SegmentTypeItemPredictedGenderValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_PredictedAge(UniversalBaseModel):
    condition_type: typing.Literal["PredictedAge"] = "PredictedAge"
    field: SegmentTypeItemPredictedAgeField
    op: SegmentTypeItemPredictedAgeOp
    value: SegmentTypeItemPredictedAgeValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SegmentTypeItem_NewSubscribers(UniversalBaseModel):
    condition_type: typing.Literal["NewSubscribers"] = "NewSubscribers"
    field: typing.Optional[SegmentTypeItemNewSubscribersField] = None
    op: typing.Optional[SegmentTypeItemNewSubscribersOp] = None
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


SegmentTypeItem = typing_extensions.Annotated[
    typing.Union[
        SegmentTypeItem_Aim,
        SegmentTypeItem_Automation,
        SegmentTypeItem_CampaignPoll,
        SegmentTypeItem_Conversation,
        SegmentTypeItem_Date,
        SegmentTypeItem_EmailClient,
        SegmentTypeItem_Language,
        SegmentTypeItem_MemberRating,
        SegmentTypeItem_SignupSource,
        SegmentTypeItem_SurveyMonkey,
        SegmentTypeItem_Vip,
        SegmentTypeItem_Interests,
        SegmentTypeItem_EcommCategory,
        SegmentTypeItem_EcommNumber,
        SegmentTypeItem_EcommPurchased,
        SegmentTypeItem_EcommSpent,
        SegmentTypeItem_EcommStore,
        SegmentTypeItem_GoalActivity,
        SegmentTypeItem_GoalTimestamp,
        SegmentTypeItem_FuzzySegment,
        SegmentTypeItem_StaticSegment,
        SegmentTypeItem_IpGeoCountryState,
        SegmentTypeItem_IpGeoIn,
        SegmentTypeItem_IpGeoInZip,
        SegmentTypeItem_IpGeoUnknown,
        SegmentTypeItem_IpGeoZip,
        SegmentTypeItem_SocialAge,
        SegmentTypeItem_SocialGender,
        SegmentTypeItem_SocialInfluence,
        SegmentTypeItem_SocialNetworkMember,
        SegmentTypeItem_SocialNetworkFollow,
        SegmentTypeItem_AddressMerge,
        SegmentTypeItem_ZipMerge,
        SegmentTypeItem_BirthdayMerge,
        SegmentTypeItem_DateMerge,
        SegmentTypeItem_SelectMerge,
        SegmentTypeItem_TextMerge,
        SegmentTypeItem_EmailAddress,
        SegmentTypeItem_PredictedGender,
        SegmentTypeItem_PredictedAge,
        SegmentTypeItem_NewSubscribers,
    ],
    pydantic.Field(discriminator="condition_type"),
]
