# This file was auto-generated by Fern from our API Definition.

import typing

SegmentTypeItemInterestsOp = typing.Union[
    typing.Literal["interestcontains", "interestcontainsall", "interestnotcontains"], typing.Any
]
