# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_social_network_follow_field import SegmentTypeItemSocialNetworkFollowField
from .segment_type_item_social_network_follow_op import SegmentTypeItemSocialNetworkFollowOp
from .segment_type_item_social_network_follow_value import SegmentTypeItemSocialNetworkFollowValue


class SegmentTypeItemSocialNetworkFollow(UniversalBaseModel):
    """
    Segment by social network in Social Profiles data.
    """

    field: SegmentTypeItemSocialNetworkFollowField = pydantic.Field()
    """
    Segment by social network in Social Profiles data.
    """

    op: SegmentTypeItemSocialNetworkFollowOp = pydantic.Field()
    """
    Members who are/not following a linked account on a given social network.
    """

    value: SegmentTypeItemSocialNetworkFollowValue = pydantic.Field()
    """
    The social network to segment against.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
