# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_ip_geo_zip_field import SegmentTypeItemIpGeoZipField
from .segment_type_item_ip_geo_zip_op import SegmentTypeItemIpGeoZipOp


class SegmentTypeItemIpGeoZip(UniversalBaseModel):
    """
    Segment by a specific US ZIP code.
    """

    field: SegmentTypeItemIpGeoZipField = pydantic.Field()
    """
    Segmenting subscribers who are within a specific location.
    """

    op: SegmentTypeItemIpGeoZipOp = pydantic.Field()
    """
    Segment members who are/are not within a specific US zip code.
    """

    value: int = pydantic.Field()
    """
    The 5-digit zip code.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
