# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_vip_field import SegmentTypeItemVipField
from .segment_type_item_vip_op import SegmentTypeItemVipOp


class SegmentTypeItemVip(UniversalBaseModel):
    """
    Segment by VIP status.
    """

    field: SegmentTypeItemVipField = pydantic.Field()
    """
    Segment by VIP status.
    """

    op: SegmentTypeItemVipOp = pydantic.Field()
    """
    Whether the member is or is not marked as VIP.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
