# This file was auto-generated by Fern from our API Definition.

import typing

SegmentTypeItemSocialNetworkMemberValue = typing.Union[
    typing.Literal[
        "twitter",
        "facebook",
        "linkedin",
        "flickr",
        "foursquare",
        "lastfm",
        "myspace",
        "quora",
        "vimeo",
        "yelp",
        "youtube",
    ],
    typing.Any,
]
