# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_automation_field import SegmentTypeItemAutomationField
from .segment_type_item_automation_op import SegmentTypeItemAutomationOp


class SegmentTypeItemAutomation(UniversalBaseModel):
    """
    Segment by interaction with an Automation workflow.
    """

    field: SegmentTypeItemAutomationField = pydantic.Field()
    """
    Segment by interaction with an Automation workflow.
    """

    op: SegmentTypeItemAutomationOp = pydantic.Field()
    """
    The status of the member with regard to the automation workflow. One of the following: has started the workflow, has completed the workflow, has not started the workflow, or has not completed the workflow.
    """

    value: str = pydantic.Field()
    """
    The web id for the automation workflow to segment against.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
