# This file was auto-generated by Fern from our API Definition.

import typing

SegmentTypeItemIpGeoCountryStateOp = typing.Union[
    typing.Literal["ipgeocountry", "ipgeonotcountry", "ipgeostate", "ipgeonotstate"], typing.Any
]
