# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_social_influence_field import SegmentTypeItemSocialInfluenceField
from .segment_type_item_social_influence_op import SegmentTypeItemSocialInfluenceOp


class SegmentTypeItemSocialInfluence(UniversalBaseModel):
    """
    Segment by influence rating in Social Profiles data.
    """

    field: SegmentTypeItemSocialInfluenceField = pydantic.Field()
    """
    Segment by influence rating in Social Profiles data.
    """

    op: SegmentTypeItemSocialInfluenceOp = pydantic.Field()
    """
    Members who have a rating that is/not or greater/less than the rating provided.
    """

    value: float = pydantic.Field()
    """
    The Social Profiles influence rating to segment.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
