# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_ip_geo_in_field import SegmentTypeItemIpGeoInField
from .segment_type_item_ip_geo_in_op import SegmentTypeItemIpGeoInOp


class SegmentTypeItemIpGeoIn(UniversalBaseModel):
    """
    Segment by a specific geographic region.
    """

    addr: str = pydantic.Field()
    """
    The address of the target location.
    """

    field: SegmentTypeItemIpGeoInField = pydantic.Field()
    """
    Segmenting subscribers who are within a specific location.
    """

    lat: str = pydantic.Field()
    """
    The latitude of the target location.
    """

    lng: str = pydantic.Field()
    """
    The longitude of the target location.
    """

    op: SegmentTypeItemIpGeoInOp = pydantic.Field()
    """
    Segment members who are within a specific geographic region.
    """

    value: int = pydantic.Field()
    """
    The radius of the target location.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
