# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_type_item_date_field import SegmentTypeItemDateField
from .segment_type_item_date_op import SegmentTypeItemDateOp


class SegmentTypeItemDate(UniversalBaseModel):
    """
    Segment by a specific date field.
    """

    extra: typing.Optional[str] = pydantic.Field(default=None)
    """
    When segmenting on 'date' or 'campaign', the date for the segment formatted as YYYY-MM-DD or the web id for the campaign.
    """

    field: SegmentTypeItemDateField = pydantic.Field()
    """
    The type of date field to segment on: The opt-in time for a signup, the date the subscriber was last updated, or the date of their last ecomm purchase.
    """

    op: SegmentTypeItemDateOp = pydantic.Field()
    """
    When the event took place:  Before, after, is a specific date, is not a specific date, is blank, or is not blank.
    """

    value: str = pydantic.Field()
    """
    What type of data to segment on: a specific date, a specific campaign, or the last campaign sent.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
