# This file was auto-generated by Fern from our API Definition.

import typing

SegmentTypeItemGoalActivityOp = typing.Union[
    typing.Literal["is", "goal_not", "contains", "goal_notcontain", "starts", "ends"], typing.Any
]
