# This file was auto-generated by Fern from our API Definition.

import typing

SignupFormHeaderImageBorderStyle = typing.Union[
    typing.Literal["none", "solid", "dotted", "dashed", "double", "groove", "outset", "inset", "ridge"], typing.Any
]
