# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .subscriber_removed_from_automation_workflow_links_item_item import (
    SubscriberRemovedFromAutomationWorkflowLinksItemItem,
)


class SubscriberRemovedFromAutomationWorkflow(UniversalBaseModel):
    """
    A summary of a subscriber removed from an Automation workflow.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[typing.List[SubscriberRemovedFromAutomationWorkflowLinksItemItem]]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    email_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    The list member's email address.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The MD5 hash of the lowercase version of the list member's email address.
    """

    list_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A string that uniquely identifies a list.
    """

    workflow_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A string that uniquely identifies an Automation workflow.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
