# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .survey_section_request_question import SurveySectionRequestQuestion
from .survey_section_request_type import SurveySectionRequestType


class SurveySectionRequest(UniversalBaseModel):
    """
    A survey section. On PATCH, include the section id to update it; omit the section from the sections array to delete it (and any question it contains).
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The section ID. On PATCH, include to update an existing section; omit to add a new section.
    """

    type: SurveySectionRequestType = pydantic.Field()
    """
    The section type.
    """

    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Rich text content for introduction or context sections.
    """

    options: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Additional section options.
    """

    question: typing.Optional[SurveySectionRequestQuestion] = pydantic.Field(default=None)
    """
    A survey question. On PATCH, include the question id to update it. Omitting question id creates a new question; it does not delete an existing one. To delete a question, omit its section from the sections array.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
