# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SurveyQuestionReportOptionsItem(UniversalBaseModel):
    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    The count of responses that selected this survey question option.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID for this survey question option.
    """

    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    The label for this survey question option.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
