# This file was auto-generated by Fern from our API Definition.

import typing

CreateAccountExportsRequestIncludeStagesItem = typing.Union[
    typing.Literal["audiences", "campaigns", "events", "gallery_files", "reports", "templates"], typing.Any
]
