# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .list_root_response import ListRootResponse
    from .list_root_response_contact import ListRootResponseContact
    from .list_root_response_first_payment import ListRootResponseFirstPayment
    from .list_root_response_first_payment_one import ListRootResponseFirstPaymentOne
    from .list_root_response_industry_stats import ListRootResponseIndustryStats
    from .list_root_response_links_item import ListRootResponseLinksItem
    from .list_root_response_links_item_method import ListRootResponseLinksItemMethod
    from .list_root_response_pricing_plan_type import ListRootResponsePricingPlanType
_dynamic_imports: typing.Dict[str, str] = {
    "ListRootResponse": ".list_root_response",
    "ListRootResponseContact": ".list_root_response_contact",
    "ListRootResponseFirstPayment": ".list_root_response_first_payment",
    "ListRootResponseFirstPaymentOne": ".list_root_response_first_payment_one",
    "ListRootResponseIndustryStats": ".list_root_response_industry_stats",
    "ListRootResponseLinksItem": ".list_root_response_links_item",
    "ListRootResponseLinksItemMethod": ".list_root_response_links_item_method",
    "ListRootResponsePricingPlanType": ".list_root_response_pricing_plan_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ListRootResponse",
    "ListRootResponseContact",
    "ListRootResponseFirstPayment",
    "ListRootResponseFirstPaymentOne",
    "ListRootResponseIndustryStats",
    "ListRootResponseLinksItem",
    "ListRootResponseLinksItemMethod",
    "ListRootResponsePricingPlanType",
]
