# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from .list_root_response_first_payment_one import ListRootResponseFirstPaymentOne

ListRootResponseFirstPayment = typing.Union[dt.datetime, ListRootResponseFirstPaymentOne]
