# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .get_campaign_folders_response import GetCampaignFoldersResponse
    from .get_campaign_folders_response_links_item import GetCampaignFoldersResponseLinksItem
    from .get_campaign_folders_response_links_item_method import GetCampaignFoldersResponseLinksItemMethod
    from .update_campaign_folders_response import UpdateCampaignFoldersResponse
    from .update_campaign_folders_response_links_item import UpdateCampaignFoldersResponseLinksItem
    from .update_campaign_folders_response_links_item_method import UpdateCampaignFoldersResponseLinksItemMethod
_dynamic_imports: typing.Dict[str, str] = {
    "GetCampaignFoldersResponse": ".get_campaign_folders_response",
    "GetCampaignFoldersResponseLinksItem": ".get_campaign_folders_response_links_item",
    "GetCampaignFoldersResponseLinksItemMethod": ".get_campaign_folders_response_links_item_method",
    "UpdateCampaignFoldersResponse": ".update_campaign_folders_response",
    "UpdateCampaignFoldersResponseLinksItem": ".update_campaign_folders_response_links_item",
    "UpdateCampaignFoldersResponseLinksItemMethod": ".update_campaign_folders_response_links_item_method",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetCampaignFoldersResponse",
    "GetCampaignFoldersResponseLinksItem",
    "GetCampaignFoldersResponseLinksItemMethod",
    "UpdateCampaignFoldersResponse",
    "UpdateCampaignFoldersResponseLinksItem",
    "UpdateCampaignFoldersResponseLinksItemMethod",
]
