# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .list_chimp_chatter_activity_feed_response_chimp_chatter_item import (
    ListChimpChatterActivityFeedResponseChimpChatterItem,
)
from .list_chimp_chatter_activity_feed_response_links_item import ListChimpChatterActivityFeedResponseLinksItem


class ListChimpChatterActivityFeedResponse(UniversalBaseModel):
    """
    An array of Chimp Chatter messages. There's a maximum of 200 messages present for an account.
    """

    links: typing_extensions.Annotated[
        typing.Optional[typing.List[ListChimpChatterActivityFeedResponseLinksItem]],
        FieldMetadata(alias="_links"),
        pydantic.Field(
            alias="_links", description="A list of link types and descriptions for the API schema documents."
        ),
    ] = None
    """
    A list of link types and descriptions for the API schema documents.
    """

    chimp_chatter: typing.Optional[typing.List[ListChimpChatterActivityFeedResponseChimpChatterItem]] = pydantic.Field(
        default=None
    )
    """
    An array of Chimp Chatter messages. There's a maximum of 200 messages present for an account.
    """

    total_items: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of items matching the query regardless of pagination.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
