# This file was auto-generated by Fern from our API Definition.

import typing

ListFacebookAdEcommerceProductActivityReportingRequestSortField = typing.Union[
    typing.Literal["title", "total_revenue", "total_purchased"], typing.Any
]
