# This file was auto-generated by Fern from our API Definition.

import typing

ListSurveyQuestionAnswersReportingResponseAnswersItemContactStatus = typing.Union[
    typing.Literal["Subscribed", "Unsubscribed", "Non-Subscribed", "Cleaned", "Archived"], typing.Any
]
