# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListFacebookAdEcommerceProductActivityReportingResponseProductsItem(UniversalBaseModel):
    currency_code: typing.Optional[str] = None
    image_url: typing.Optional[str] = None
    recommendation_purchased: typing.Optional[int] = None
    recommendation_total: typing.Optional[int] = None
    sku: typing.Optional[str] = None
    title: typing.Optional[str] = None
    total_purchased: typing.Optional[float] = None
    total_revenue: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
