# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_survey_question_answers_reporting_response_answers_item_contact import (
    ListSurveyQuestionAnswersReportingResponseAnswersItemContact,
)


class ListSurveyQuestionAnswersReportingResponseAnswersItem(UniversalBaseModel):
    """
    The details of a survey question's answer.
    """

    contact: typing.Optional[ListSurveyQuestionAnswersReportingResponseAnswersItemContact] = pydantic.Field(
        default=None
    )
    """
    Information about the contact.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the answer.
    """

    is_new_contact: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If this contact was added to the Mailchimp audience via this survey.
    """

    response_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the survey response.
    """

    submitted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time when the survey response was submitted in ISO 8601 format.
    """

    value: typing.Optional[str] = pydantic.Field(default=None)
    """
    The raw text answer.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
