# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .get_authorized_apps_response import GetAuthorizedAppsResponse
    from .get_authorized_apps_response_links_item import GetAuthorizedAppsResponseLinksItem
    from .get_authorized_apps_response_links_item_method import GetAuthorizedAppsResponseLinksItemMethod
    from .list_authorized_apps_response import ListAuthorizedAppsResponse
    from .list_authorized_apps_response_apps_item import ListAuthorizedAppsResponseAppsItem
    from .list_authorized_apps_response_apps_item_links_item import ListAuthorizedAppsResponseAppsItemLinksItem
    from .list_authorized_apps_response_apps_item_links_item_method import (
        ListAuthorizedAppsResponseAppsItemLinksItemMethod,
    )
    from .list_authorized_apps_response_links_item import ListAuthorizedAppsResponseLinksItem
    from .list_authorized_apps_response_links_item_method import ListAuthorizedAppsResponseLinksItemMethod
_dynamic_imports: typing.Dict[str, str] = {
    "GetAuthorizedAppsResponse": ".get_authorized_apps_response",
    "GetAuthorizedAppsResponseLinksItem": ".get_authorized_apps_response_links_item",
    "GetAuthorizedAppsResponseLinksItemMethod": ".get_authorized_apps_response_links_item_method",
    "ListAuthorizedAppsResponse": ".list_authorized_apps_response",
    "ListAuthorizedAppsResponseAppsItem": ".list_authorized_apps_response_apps_item",
    "ListAuthorizedAppsResponseAppsItemLinksItem": ".list_authorized_apps_response_apps_item_links_item",
    "ListAuthorizedAppsResponseAppsItemLinksItemMethod": ".list_authorized_apps_response_apps_item_links_item_method",
    "ListAuthorizedAppsResponseLinksItem": ".list_authorized_apps_response_links_item",
    "ListAuthorizedAppsResponseLinksItemMethod": ".list_authorized_apps_response_links_item_method",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetAuthorizedAppsResponse",
    "GetAuthorizedAppsResponseLinksItem",
    "GetAuthorizedAppsResponseLinksItemMethod",
    "ListAuthorizedAppsResponse",
    "ListAuthorizedAppsResponseAppsItem",
    "ListAuthorizedAppsResponseAppsItemLinksItem",
    "ListAuthorizedAppsResponseAppsItemLinksItemMethod",
    "ListAuthorizedAppsResponseLinksItem",
    "ListAuthorizedAppsResponseLinksItemMethod",
]
